/**
 * Localized legal content — Terms of Service + Privacy Policy for InnFeel.
 * All substance preserved across languages; shorter phrasing in some for compactness.
 * English (en) is the canonical legal version — other languages are informational translations
 * and ship alongside the English baseline for UX.
 */

import { LocaleCode } from "./i18n";

export type LegalSection = { h: string; body: string[] }; // h = heading, body = paragraphs (markdown-lite)
export type LegalDoc = { title: string; effective: string; intro: string; sections: LegalSection[]; contactIntro: string; contactEmail: string };

export const EFFECTIVE_DATE = "June 1, 2025";

// --------------------- TERMS OF SERVICE ---------------------
const TERMS: Record<LocaleCode, LegalDoc> = {
  en: {
    title: "InnFeel — Terms of Service",
    effective: "Effective date: " + EFFECTIVE_DATE,
    intro: "These Terms of Service (\"Terms\") govern your access to and use of the InnFeel mobile application and related services (the \"Service\"), operated by InnFeel (\"we\", \"us\", \"our\"). By creating an account or using InnFeel, you agree to these Terms. If you do not agree, do not use the Service.",
    sections: [
      { h: "1. Who may use InnFeel", body: ["You must be at least 13 years old (16 in the EEA/UK where required by local law) and able to form a binding contract."] },
      { h: "2. Your account", body: ["You are responsible for keeping your credentials confidential and for all activity under your account. You must provide accurate information. Notify us at support@innfeel.app of any unauthorised use."] },
      { h: "3. User content", body: ["You retain ownership of the auras, photos, videos, text, audio notes and other content you submit (\"User Content\"). By submitting User Content you grant us a worldwide, non-exclusive, royalty-free, sub-licensable licence to host, store, reproduce, display, adapt and distribute it solely to operate, improve and secure the Service. This licence ends when you delete the content or your account, except for: backups retained up to 30 days, content already shared with friends, and where retention is required by law.", "You are solely responsible for your User Content. You must not post anything unlawful, defamatory, harassing, sexually explicit involving minors, infringing, or hateful. We may remove content and suspend accounts to enforce these Terms or applicable law."] },
      { h: "4. Acceptable use", body: ["You must not: reverse-engineer or scrape the Service; circumvent security or reciprocity rules; impersonate anyone; spam or harass; introduce malware; resell the Service without our written permission."] },
      { h: "5. Subscriptions, billing and no-refund policy", body: ["InnFeel offers a free tier and a paid \"Pro\" subscription. Pro is billed recurrently via the Apple App Store, Google Play, Stripe or other authorised provider, at the price shown in-app (taxes excluded unless stated). Subscriptions renew automatically unless cancelled before renewal.", "**No refunds.** Except where required by mandatory applicable law, **all payments are final and non-refundable, including for any billing period already started, unused time, or accidental renewals**. Free-trial periods (if offered) convert into paid subscriptions automatically unless cancelled before the trial ends.", "**You are responsible for cancelling your subscription** directly with the billing provider: Apple (Settings → your name → Subscriptions → InnFeel), Google (Play Store → Payments & subscriptions), or Stripe via the customer portal or support@innfeel.app.", "Deleting your InnFeel account does **not** cancel a subscription billed by Apple, Google or Stripe — cancel it with the provider separately. We cannot issue refunds for periods already paid.", "EU/UK: by subscribing you expressly request immediate performance of digital content and waive your 14-day withdrawal right to the extent permitted."] },
      { h: "6. Changes to the Service and pricing", body: ["We may add, modify or remove features and change pricing. Price changes apply from the next renewal cycle and are notified where required by law."] },
      { h: "7. Termination", body: ["You may delete your account at any time from Settings → Account. We may suspend or terminate access immediately if you breach these Terms, create risk, or for lawful business reasons."] },
      { h: "8. Disclaimers", body: ["InnFeel is provided \"AS IS\". To the maximum extent permitted by law, we disclaim all warranties, express or implied. InnFeel is **not a medical device** and does not provide medical advice. If you are in crisis, contact local emergency services or a qualified professional."] },
      { h: "9. Limitation of liability", body: ["To the maximum extent permitted by law, we and our affiliates will not be liable for any indirect, incidental, special, consequential or punitive damages. Our aggregate liability is limited to the greater of the amount you paid us in the 12 months before the claim or USD 50."] },
      { h: "10. Indemnification", body: ["You agree to defend, indemnify and hold us harmless from claims arising from your User Content, your use of the Service, or your violation of these Terms or any law."] },
      { h: "11. Third-party services", body: ["The Service integrates third parties (Apple/Google IAP, Stripe, RevenueCat, Apple Music, Spotify, Expo Push, AI providers). Their terms apply to their portions."] },
      { h: "12. Governing law", body: ["These Terms are governed by the laws of the country of our principal place of business, without prejudice to mandatory consumer law in your jurisdiction."] },
      { h: "13. Apple / Google additional terms", body: ["If you downloaded the app from Apple or Google, these Terms are between you and us, not the platform. Apple and Google are third-party beneficiaries and may enforce these Terms."] },
      { h: "14. Changes to these Terms", body: ["We may update these Terms. Material changes will be notified in-app. Continued use after the effective date constitutes acceptance."] },
    ],
    contactIntro: "Questions? Email",
    contactEmail: "support@innfeel.app",
  },

  fr: {
    title: "InnFeel — Conditions Générales d'Utilisation et de Vente",
    effective: "Date d'effet : 1er juin 2025",
    intro: "Les présentes Conditions (« CGU/CGV ») régissent votre accès à l'application mobile InnFeel et aux services associés (le « Service »), exploités par InnFeel (« nous »). En créant un compte ou en utilisant InnFeel, vous acceptez ces Conditions. Si vous n'êtes pas d'accord, n'utilisez pas le Service.",
    sections: [
      { h: "1. Qui peut utiliser InnFeel", body: ["Vous devez avoir au moins 13 ans (16 dans l'EEE/RU si requis) et pouvoir conclure un contrat."] },
      { h: "2. Votre compte", body: ["Vous êtes responsable de la confidentialité de vos identifiants et de toute activité sur votre compte. Fournissez des informations exactes. Signalez tout usage non autorisé à support@innfeel.app."] },
      { h: "3. Vos contenus", body: ["Vous conservez la propriété de vos auras, photos, vidéos, textes, notes vocales et autres contenus (« Contenus Utilisateur »). En les soumettant vous nous accordez une licence mondiale, non exclusive, gratuite et sous-licenciable pour les héberger, stocker, reproduire, afficher, adapter et distribuer uniquement pour opérer, améliorer et sécuriser le Service. Cette licence prend fin quand vous supprimez le contenu ou votre compte, sauf sauvegardes (≤ 30 jours), contenus déjà partagés avec des amis, ou obligations légales.", "Vous êtes seul responsable de vos Contenus Utilisateur. Il est interdit de publier du contenu illégal, diffamatoire, harcelant, sexuellement explicite impliquant des mineurs, contrefaisant ou haineux. Nous pouvons supprimer du contenu et suspendre des comptes."] },
      { h: "4. Utilisation acceptable", body: ["Il est interdit de : faire de la rétro-ingénierie, scraper le Service, contourner la sécurité ou la règle de réciprocité, usurper une identité, spammer ou harceler, introduire des logiciels malveillants, revendre le Service sans autorisation écrite."] },
      { h: "5. Abonnements, facturation et NON-remboursement", body: ["InnFeel offre une version gratuite et un abonnement « Pro » payant. Pro est facturé de manière récurrente via l'App Store Apple, Google Play, Stripe ou un autre prestataire autorisé, au prix affiché dans l'app (taxes exclues sauf indication). Les abonnements se renouvellent automatiquement sauf résiliation avant renouvellement.", "**Aucun remboursement.** Sauf obligation légale impérative, **tout paiement est ferme et non remboursable, y compris pour toute période de facturation déjà commencée, période non utilisée, ou renouvellement accidentel**. Les périodes d'essai (si proposées) se convertissent automatiquement en abonnement payant sauf résiliation avant leur fin.", "**Vous êtes responsable de résilier votre abonnement** directement auprès du prestataire de facturation : Apple (Réglages → votre nom → Abonnements → InnFeel), Google (Play Store → Paiements et abonnements), ou Stripe via le portail client ou support@innfeel.app.", "La suppression de votre compte InnFeel **ne résilie pas** un abonnement facturé par Apple, Google ou Stripe — vous devez le résilier séparément. Aucun remboursement ne sera effectué pour des périodes déjà payées.", "UE/RU : en souscrivant, vous demandez expressément l'exécution immédiate du contenu numérique et renoncez, dans la mesure autorisée, à votre droit de rétractation de 14 jours."] },
      { h: "6. Modifications du Service et des prix", body: ["Nous pouvons ajouter, modifier ou retirer des fonctionnalités et modifier les prix. Les changements de prix s'appliquent au prochain cycle de renouvellement et sont notifiés si la loi l'exige."] },
      { h: "7. Résiliation", body: ["Vous pouvez supprimer votre compte à tout moment depuis Paramètres → Compte. Nous pouvons suspendre ou résilier immédiatement en cas de violation, risque, ou motifs légitimes."] },
      { h: "8. Garanties", body: ["InnFeel est fourni « EN L'ÉTAT ». Dans la mesure maximale permise, nous déclinons toute garantie expresse ou implicite. InnFeel **n'est pas un dispositif médical** et ne fournit pas d'avis médical. En cas de crise, contactez les services d'urgence locaux."] },
      { h: "9. Limitation de responsabilité", body: ["Dans la mesure maximale permise, nous et nos affiliés ne serons pas responsables des dommages indirects, incidents, spéciaux, consécutifs ou punitifs. Notre responsabilité globale est limitée au plus élevé du montant payé dans les 12 derniers mois ou 50 USD."] },
      { h: "10. Indemnisation", body: ["Vous acceptez de nous défendre, indemniser et dégager de toute responsabilité pour les réclamations liées à vos Contenus, votre usage du Service, ou votre violation des Conditions ou de la loi."] },
      { h: "11. Services tiers", body: ["Le Service intègre des tiers (Apple/Google IAP, Stripe, RevenueCat, Apple Music, Spotify, Expo Push, fournisseurs IA). Leurs conditions s'appliquent à leurs parties."] },
      { h: "12. Droit applicable", body: ["Les présentes Conditions sont régies par le droit du pays de notre principal établissement, sans préjudice des lois de consommation impératives de votre juridiction."] },
      { h: "13. Conditions Apple / Google additionnelles", body: ["Si vous avez téléchargé l'app chez Apple ou Google, ces Conditions lient vous et nous, pas la plateforme. Apple et Google sont bénéficiaires tiers et peuvent les faire respecter."] },
      { h: "14. Modifications des Conditions", body: ["Nous pouvons les mettre à jour. Les modifications importantes sont notifiées dans l'app. L'utilisation continue vaut acceptation."] },
    ],
    contactIntro: "Questions ? Email",
    contactEmail: "support@innfeel.app",
  },

  es: {
    title: "InnFeel — Términos de Servicio",
    effective: "Fecha de vigencia: 1 de junio de 2025",
    intro: "Estos Términos rigen tu acceso y uso de la aplicación móvil InnFeel y servicios relacionados (el \"Servicio\"), operado por InnFeel (\"nosotros\"). Al crear una cuenta o usar InnFeel, aceptas estos Términos. Si no aceptas, no uses el Servicio.",
    sections: [
      { h: "1. Quién puede usar InnFeel", body: ["Debes tener al menos 13 años (16 en EEE/RU donde lo exige la ley local) y poder celebrar un contrato vinculante."] },
      { h: "2. Tu cuenta", body: ["Eres responsable de la confidencialidad de tus credenciales y de toda actividad bajo tu cuenta. Informa de usos no autorizados a support@innfeel.app."] },
      { h: "3. Contenido del usuario", body: ["Conservas la propiedad de tus auras, fotos, vídeos, textos, notas de audio y demás contenido que envíes. Al enviarlo, nos concedes una licencia mundial, no exclusiva, gratuita y sublicenciable para alojarlo, reproducirlo, mostrarlo, adaptarlo y distribuirlo únicamente para operar, mejorar y asegurar el Servicio. Esta licencia termina cuando borres el contenido o tu cuenta, salvo copias de seguridad (≤ 30 días), contenido ya compartido y obligaciones legales.", "Eres responsable de tu contenido. Está prohibido publicar contenido ilegal, difamatorio, acosador, sexualmente explícito con menores, infractor u odioso. Podemos eliminarlo y suspender cuentas."] },
      { h: "4. Uso aceptable", body: ["No debes: hacer ingeniería inversa, scraping, eludir la seguridad o reciprocidad, suplantar identidad, spam/acoso, introducir malware, revender el Servicio sin permiso."] },
      { h: "5. Suscripciones y política de NO reembolso", body: ["InnFeel ofrece plan gratuito y suscripción \"Pro\" de pago. Pro se factura de forma recurrente vía App Store de Apple, Google Play, Stripe u otro proveedor, al precio mostrado (impuestos excluidos salvo indicación). Las suscripciones se renuevan automáticamente salvo cancelación previa.", "**Sin reembolsos.** Salvo donde lo exija ley imperativa aplicable, **todos los pagos son finales y no reembolsables, incluido cualquier período de facturación ya iniciado, tiempo no usado o renovaciones accidentales**. Los períodos de prueba (si se ofrecen) se convierten automáticamente en suscripción de pago.", "**Eres responsable de cancelar tu suscripción** directamente con el proveedor: Apple (Ajustes → tu nombre → Suscripciones → InnFeel), Google (Play Store → Pagos y suscripciones), Stripe (portal del cliente o support@innfeel.app).", "Borrar tu cuenta InnFeel **no cancela** una suscripción de Apple, Google o Stripe — cancélala aparte. No emitimos reembolsos por períodos ya pagados.", "UE/RU: al suscribirte solicitas la ejecución inmediata del contenido digital y renuncias, en la medida permitida, al derecho de desistimiento de 14 días."] },
      { h: "6. Cambios en el Servicio y precios", body: ["Podemos añadir, modificar o eliminar funciones y cambiar precios. Los cambios se aplican desde el siguiente ciclo y se notifican cuando la ley lo exige."] },
      { h: "7. Terminación", body: ["Puedes borrar tu cuenta en cualquier momento en Ajustes → Cuenta. Podemos suspender o terminar el acceso inmediatamente por incumplimientos, riesgos o causas legítimas."] },
      { h: "8. Exenciones", body: ["InnFeel se proporciona \"TAL CUAL\". En la máxima medida permitida rechazamos todas las garantías. InnFeel **no es un dispositivo médico** ni ofrece consejo médico. En caso de crisis, contacta servicios de emergencia locales."] },
      { h: "9. Limitación de responsabilidad", body: ["En la máxima medida permitida, no seremos responsables de daños indirectos, incidentales, especiales, consecuentes o punitivos. Nuestra responsabilidad agregada se limita al mayor de lo pagado en los últimos 12 meses o 50 USD."] },
      { h: "10. Indemnización", body: ["Aceptas defendernos e indemnizarnos frente a reclamaciones derivadas de tu Contenido, uso del Servicio o incumplimiento de estos Términos o la ley."] },
      { h: "11. Servicios de terceros", body: ["Integramos terceros (IAP Apple/Google, Stripe, RevenueCat, Apple Music, Spotify, Expo Push, IA). Sus condiciones aplican a sus partes."] },
      { h: "12. Ley aplicable", body: ["Estos Términos se rigen por la ley del país de nuestro establecimiento principal, sin perjuicio de la ley de consumidor imperativa de tu jurisdicción."] },
      { h: "13. Condiciones Apple / Google", body: ["Si descargaste la app de Apple o Google, estos Términos son entre tú y nosotros, no la plataforma. Apple y Google son beneficiarios terceros."] },
      { h: "14. Cambios en los Términos", body: ["Podemos actualizarlos. Los cambios importantes se notifican en la app. El uso continuado implica aceptación."] },
    ],
    contactIntro: "¿Preguntas? Email",
    contactEmail: "support@innfeel.app",
  },

  it: {
    title: "InnFeel — Termini di Servizio",
    effective: "Data di efficacia: 1 giugno 2025",
    intro: "Questi Termini regolano il tuo accesso e uso dell'app InnFeel e dei servizi correlati (il \"Servizio\"), gestito da InnFeel (\"noi\"). Creando un account o usando InnFeel, accetti questi Termini. Se non accetti, non usare il Servizio.",
    sections: [
      { h: "1. Chi può usare InnFeel", body: ["Devi avere almeno 13 anni (16 in SEE/Regno Unito se richiesto) e capacità di contrarre."] },
      { h: "2. Il tuo account", body: ["Sei responsabile della riservatezza delle credenziali e di tutte le attività sul tuo account. Segnala usi non autorizzati a support@innfeel.app."] },
      { h: "3. Contenuti utente", body: ["Mantieni la proprietà dei tuoi auras, foto, video, testi, note audio e altri contenuti. Inviandoli ci concedi una licenza mondiale, non esclusiva, gratuita e sublicenziabile per ospitarli, riprodurli, visualizzarli, adattarli e distribuirli solo per operare, migliorare e proteggere il Servizio. La licenza termina quando cancelli il contenuto o l'account, salvo backup (≤ 30 giorni), contenuti già condivisi e obblighi di legge.", "Sei l'unico responsabile dei tuoi contenuti. Vietato pubblicare contenuti illegali, diffamatori, molesti, sessualmente espliciti con minori, contraffatti o d'odio. Possiamo rimuoverli e sospendere account."] },
      { h: "4. Uso accettabile", body: ["Vietato: reverse-engineering, scraping, aggirare la sicurezza o la reciprocità, impersonare altri, spam/molestie, introdurre malware, rivendere il Servizio."] },
      { h: "5. Abbonamenti e politica di NON rimborso", body: ["InnFeel offre piano gratuito e abbonamento \"Pro\". Pro è fatturato ricorrentemente tramite App Store Apple, Google Play, Stripe o altro fornitore, al prezzo in-app (tasse escluse salvo diversa indicazione). Rinnovo automatico salvo disdetta prima del rinnovo.", "**Nessun rimborso.** Salvo legge imperativa applicabile, **tutti i pagamenti sono definitivi e non rimborsabili, inclusi periodi già iniziati, tempo non usato o rinnovi accidentali**. I periodi di prova (se offerti) si convertono automaticamente in abbonamento a pagamento.", "**Sei responsabile della disdetta del tuo abbonamento** direttamente col fornitore: Apple (Impostazioni → tuo nome → Abbonamenti), Google (Play Store → Pagamenti e abbonamenti), Stripe (portale cliente o support@innfeel.app).", "Cancellare l'account InnFeel **non annulla** un abbonamento fatturato da Apple, Google o Stripe — annullalo separatamente. Non emettiamo rimborsi per periodi già pagati.", "UE/RU: sottoscrivendo richiedi l'esecuzione immediata del contenuto digitale e rinunci, nei limiti consentiti, al diritto di recesso di 14 giorni."] },
      { h: "6. Modifiche al Servizio e ai prezzi", body: ["Possiamo aggiungere, modificare o rimuovere funzioni e cambiare i prezzi. Le modifiche si applicano dal prossimo ciclo e sono notificate se richiesto."] },
      { h: "7. Risoluzione", body: ["Puoi eliminare il tuo account in qualsiasi momento da Impostazioni → Account. Possiamo sospendere o risolvere l'accesso immediatamente in caso di violazione, rischio o motivi legittimi."] },
      { h: "8. Esclusioni", body: ["InnFeel è fornito \"COSÌ COM'È\". Nei limiti massimi consentiti escludiamo tutte le garanzie. InnFeel **non è un dispositivo medico** e non fornisce consigli medici. In caso di crisi, contatta i servizi di emergenza."] },
      { h: "9. Limitazione di responsabilità", body: ["Nei limiti massimi consentiti, non saremo responsabili per danni indiretti, accidentali, speciali, consequenziali o punitivi. La nostra responsabilità aggregata è limitata al maggiore tra quanto pagato negli ultimi 12 mesi o 50 USD."] },
      { h: "10. Indennizzo", body: ["Accetti di difenderci e tenerci indenni da reclami derivanti dai tuoi contenuti, dall'uso del Servizio o dalla violazione di questi Termini."] },
      { h: "11. Servizi di terzi", body: ["Integriamo terzi (IAP Apple/Google, Stripe, RevenueCat, Apple Music, Spotify, Expo Push, IA). I loro termini si applicano."] },
      { h: "12. Legge applicabile", body: ["Questi Termini sono regolati dalla legge del paese della nostra sede principale, salvo leggi consumeristiche imperative del tuo paese."] },
      { h: "13. Condizioni Apple / Google", body: ["Se hai scaricato l'app da Apple o Google, questi Termini sono tra te e noi, non la piattaforma. Apple e Google sono beneficiari terzi."] },
      { h: "14. Modifiche ai Termini", body: ["Possiamo aggiornarli. Le modifiche importanti sono notificate nell'app. L'uso continuato costituisce accettazione."] },
    ],
    contactIntro: "Domande? Email",
    contactEmail: "support@innfeel.app",
  },

  de: {
    title: "InnFeel — Nutzungsbedingungen",
    effective: "Gültigkeitsdatum: 1. Juni 2025",
    intro: "Diese Nutzungsbedingungen regeln deinen Zugang zur InnFeel-App und den zugehörigen Diensten (der „Dienst\"), betrieben von InnFeel („wir\"). Durch Anmeldung oder Nutzung akzeptierst du diese Bedingungen. Wenn du nicht zustimmst, nutze den Dienst nicht.",
    sections: [
      { h: "1. Wer InnFeel nutzen darf", body: ["Du musst mindestens 13 Jahre alt sein (16 im EWR/UK, wo erforderlich) und einen Vertrag abschließen können."] },
      { h: "2. Dein Konto", body: ["Du bist für die Vertraulichkeit deiner Zugangsdaten und alle Aktivitäten in deinem Konto verantwortlich. Melde unbefugte Nutzung an support@innfeel.app."] },
      { h: "3. Nutzerinhalte", body: ["Du behältst das Eigentum an deinen Auren, Fotos, Videos, Texten, Audiomemos und anderen Inhalten. Mit der Übermittlung gewährst du uns eine weltweite, nicht-exklusive, unentgeltliche, unterlizenzierbare Lizenz, sie ausschließlich zum Betrieb, zur Verbesserung und Sicherung des Dienstes zu hosten, reproduzieren, anzeigen, anzupassen und zu verteilen. Die Lizenz endet mit Löschung des Inhalts oder Kontos, außer: Backups (≤ 30 Tage), bereits geteilte Inhalte, gesetzliche Pflichten.", "Du bist für deine Inhalte verantwortlich. Verboten sind illegale, verleumderische, belästigende, sexuell explizite Inhalte mit Minderjährigen, verletzende oder hasserfüllte Inhalte. Wir können Inhalte entfernen und Konten sperren."] },
      { h: "4. Zulässige Nutzung", body: ["Verboten: Reverse Engineering, Scraping, Umgehung von Sicherheit oder Reziprozität, Identitätsbetrug, Spam/Belästigung, Malware, unbefugter Weiterverkauf."] },
      { h: "5. Abonnements, Abrechnung und KEINE Rückerstattung", body: ["InnFeel bietet eine kostenlose Stufe und ein kostenpflichtiges „Pro\"-Abonnement. Pro wird wiederkehrend über Apple App Store, Google Play, Stripe oder einen anderen autorisierten Anbieter abgerechnet, zum im App angezeigten Preis (ohne Steuern, sofern nicht anders angegeben). Abonnements verlängern sich automatisch, sofern nicht vorher gekündigt.", "**Keine Rückerstattungen.** Außer wenn zwingendes Recht es verlangt, **sind alle Zahlungen endgültig und nicht erstattungsfähig, einschließlich bereits begonnener Abrechnungsperioden, ungenutzter Zeit oder versehentlicher Verlängerungen**. Testzeiträume (falls angeboten) werden automatisch in zahlungspflichtige Abonnements umgewandelt.", "**Du bist selbst für die Kündigung deines Abonnements verantwortlich** beim jeweiligen Anbieter: Apple (Einstellungen → dein Name → Abonnements → InnFeel), Google (Play Store → Zahlungen und Abonnements), Stripe (Kundenportal oder support@innfeel.app).", "Das Löschen deines InnFeel-Kontos **kündigt kein** Abonnement bei Apple, Google oder Stripe — das muss separat geschehen. Keine Rückerstattungen für bereits bezahlte Perioden.", "EU/UK: Mit dem Abschluss verlangst du ausdrücklich die sofortige Ausführung und verzichtest, soweit zulässig, auf dein 14-tägiges Widerrufsrecht."] },
      { h: "6. Änderungen des Dienstes und der Preise", body: ["Wir können Funktionen ergänzen, ändern oder entfernen und Preise anpassen. Preisänderungen gelten ab dem nächsten Verlängerungszyklus und werden, wo gesetzlich erforderlich, angekündigt."] },
      { h: "7. Beendigung", body: ["Du kannst dein Konto jederzeit unter Einstellungen → Konto löschen. Wir können den Zugang bei Verstößen, Risiken oder legitimen Gründen sofort sperren."] },
      { h: "8. Haftungsausschluss", body: ["InnFeel wird „WIE BESEHEN\" bereitgestellt. Im gesetzlich zulässigen Höchstmaß schließen wir alle Garantien aus. InnFeel ist **kein Medizinprodukt** und gibt keine medizinische Beratung. In Krisensituationen kontaktiere Notdienste."] },
      { h: "9. Haftungsbeschränkung", body: ["Im gesetzlich zulässigen Höchstmaß haften wir nicht für indirekte, zufällige, besondere, Folge- oder Strafschäden. Unsere Gesamthaftung ist auf den höheren Betrag von 50 USD oder der in den letzten 12 Monaten gezahlten Summe begrenzt."] },
      { h: "10. Freistellung", body: ["Du verpflichtest dich, uns von Ansprüchen freizustellen, die aus deinen Inhalten, deiner Nutzung oder Verstößen gegen diese Bedingungen entstehen."] },
      { h: "11. Drittdienste", body: ["Der Dienst integriert Dritte (Apple/Google IAP, Stripe, RevenueCat, Apple Music, Spotify, Expo Push, KI-Anbieter). Deren Bedingungen gelten für ihre Teile."] },
      { h: "12. Anwendbares Recht", body: ["Es gilt das Recht des Landes unseres Hauptsitzes, unbeschadet zwingender Verbraucherrechte in deinem Land."] },
      { h: "13. Zusätzliche Apple/Google-Bedingungen", body: ["Wenn du die App bei Apple oder Google heruntergeladen hast, bestehen diese Bedingungen zwischen dir und uns, nicht der Plattform. Apple und Google sind Drittbegünstigte."] },
      { h: "14. Änderungen", body: ["Wir können diese Bedingungen aktualisieren. Wesentliche Änderungen werden in der App angekündigt. Die fortgesetzte Nutzung gilt als Zustimmung."] },
    ],
    contactIntro: "Fragen? E-Mail",
    contactEmail: "support@innfeel.app",
  },

  pt: {
    title: "InnFeel — Termos de Serviço",
    effective: "Data de vigência: 1 de junho de 2025",
    intro: "Estes Termos regem o teu acesso e uso da aplicação InnFeel e serviços relacionados (o \"Serviço\"), operado pela InnFeel (\"nós\"). Ao criares conta ou usares InnFeel, aceitas estes Termos. Se não concordas, não uses o Serviço.",
    sections: [
      { h: "1. Quem pode usar InnFeel", body: ["Deves ter pelo menos 13 anos (16 no EEE/RU quando exigido) e capacidade para contratar."] },
      { h: "2. A tua conta", body: ["És responsável pela confidencialidade das credenciais e atividade na tua conta. Reporta usos não autorizados a support@innfeel.app."] },
      { h: "3. Conteúdo do utilizador", body: ["Manténs a propriedade das tuas auras, fotos, vídeos, textos, notas de áudio e demais conteúdo. Ao submeteres, concedes-nos uma licença mundial, não exclusiva, gratuita e sublicenciável para alojar, reproduzir, exibir, adaptar e distribuir apenas para operar, melhorar e proteger o Serviço. Termina ao apagares o conteúdo ou conta, salvo backups (≤ 30 dias), conteúdo já partilhado e obrigações legais.", "És o único responsável pelo teu conteúdo. Proibido publicar conteúdo ilegal, difamatório, assediante, sexualmente explícito com menores, infrator ou de ódio. Podemos remover conteúdo e suspender contas."] },
      { h: "4. Uso aceitável", body: ["Proibido: engenharia reversa, scraping, contornar segurança ou reciprocidade, personificação, spam/assédio, malware, revenda sem autorização."] },
      { h: "5. Subscrições e política de NÃO reembolso", body: ["InnFeel oferece plano gratuito e subscrição \"Pro\" paga. Pro é faturado recorrentemente via Apple App Store, Google Play, Stripe ou outro fornecedor, ao preço exibido (sem impostos salvo indicação). Renovação automática salvo cancelamento prévio.", "**Sem reembolsos.** Exceto onde a lei imperativa o exija, **todos os pagamentos são definitivos e não reembolsáveis, incluindo períodos já iniciados, tempo não usado ou renovações acidentais**. Períodos de teste (se oferecidos) convertem-se automaticamente em subscrição paga.", "**És responsável por cancelar a tua subscrição** diretamente com o fornecedor: Apple (Definições → teu nome → Subscrições), Google (Play Store → Pagamentos e subscrições), Stripe (portal do cliente ou support@innfeel.app).", "Apagar a tua conta InnFeel **não cancela** uma subscrição faturada por Apple, Google ou Stripe — cancela-a separadamente. Não emitimos reembolsos para períodos já pagos.", "UE/RU: ao subscreveres solicitas a execução imediata do conteúdo digital e renuncias, na medida permitida, ao direito de retratação de 14 dias."] },
      { h: "6. Alterações do Serviço e preços", body: ["Podemos acrescentar, modificar ou remover funcionalidades e alterar preços. Alterações aplicam-se no próximo ciclo e são notificadas quando exigido."] },
      { h: "7. Término", body: ["Podes apagar a conta a qualquer momento em Definições → Conta. Podemos suspender ou terminar o acesso imediatamente em caso de violação, risco ou motivos legítimos."] },
      { h: "8. Exclusões", body: ["InnFeel é fornecido \"TAL COMO ESTÁ\". No máximo permitido, rejeitamos todas as garantias. InnFeel **não é dispositivo médico** e não fornece aconselhamento médico. Em crise, contacta serviços de emergência."] },
      { h: "9. Limitação de responsabilidade", body: ["No máximo permitido, não seremos responsáveis por danos indiretos, incidentais, especiais, consequentes ou punitivos. Responsabilidade agregada limitada ao maior entre 50 USD ou o pago nos últimos 12 meses."] },
      { h: "10. Indemnização", body: ["Concordas em defender-nos e indemnizar-nos por reclamações decorrentes do teu conteúdo, uso do Serviço ou violação destes Termos."] },
      { h: "11. Serviços de terceiros", body: ["Integramos terceiros (IAP Apple/Google, Stripe, RevenueCat, Apple Music, Spotify, Expo Push, IA). As suas condições aplicam-se."] },
      { h: "12. Lei aplicável", body: ["Estes Termos regem-se pela lei do país da nossa sede, sem prejuízo de leis de consumo imperativas da tua jurisdição."] },
      { h: "13. Condições Apple / Google", body: ["Se descarregaste a app da Apple ou Google, estes Termos são entre ti e nós, não a plataforma. Apple e Google são beneficiários terceiros."] },
      { h: "14. Alterações aos Termos", body: ["Podemos atualizá-los. Alterações importantes são notificadas na app. O uso continuado implica aceitação."] },
    ],
    contactIntro: "Perguntas? Email",
    contactEmail: "support@innfeel.app",
  },

  ar: {
    title: "InnFeel — شروط الخدمة",
    effective: "تاريخ السريان: 1 يونيو 2025",
    intro: "تحكم هذه الشروط وصولك إلى تطبيق InnFeel والخدمات المرتبطة (\"الخدمة\") التي تشغلها InnFeel (\"نحن\"). بإنشاء حساب أو استخدام InnFeel فإنك توافق على هذه الشروط. إذا لم توافق، فلا تستخدم الخدمة.",
    sections: [
      { h: "1. من يمكنه استخدام InnFeel", body: ["يجب أن يكون عمرك 13 عامًا على الأقل (16 في المنطقة الاقتصادية الأوروبية/المملكة المتحدة عند الاقتضاء) وقادرًا على إبرام عقد."] },
      { h: "2. حسابك", body: ["أنت مسؤول عن سرية بيانات الاعتماد وأي نشاط على حسابك. أبلغنا عن أي استخدام غير مصرح به عبر support@innfeel.app."] },
      { h: "3. محتوى المستخدم", body: ["تحتفظ بملكية هالاتك وصورك وفيديوهاتك ونصوصك وملاحظاتك الصوتية وغيرها. بتقديمها تمنحنا ترخيصًا عالميًا غير حصري ومجانيًا وقابلًا للترخيص من الباطن لاستضافتها ونسخها وعرضها وتكييفها وتوزيعها فقط لتشغيل الخدمة وتحسينها وتأمينها. ينتهي هذا الترخيص عند حذف المحتوى أو حسابك، باستثناء النسخ الاحتياطية (حتى 30 يومًا) والمحتوى المشارك بالفعل والالتزامات القانونية.", "أنت وحدك المسؤول عن محتواك. يُحظر نشر أي محتوى غير قانوني أو تشهيري أو تحرشي أو جنسي صريح يتعلق بالقصر أو منتهك للحقوق أو يحض على الكراهية. يمكننا إزالة المحتوى وتعليق الحسابات."] },
      { h: "4. الاستخدام المقبول", body: ["يُحظر: الهندسة العكسية، الاستخراج الآلي، تجاوز الأمان أو قاعدة المعاملة بالمثل، انتحال الشخصية، الإزعاج/التحرش، إدخال برامج ضارة، إعادة البيع دون إذن."] },
      { h: "5. الاشتراكات وسياسة عدم الاسترداد", body: ["يقدم InnFeel طبقة مجانية واشتراك \"Pro\" مدفوع. يُفوتر Pro بشكل متكرر عبر App Store أو Google Play أو Stripe أو مزود معتمد آخر بالسعر الموضح في التطبيق (الضرائب مستثناة ما لم يُذكر خلاف ذلك). تتجدد الاشتراكات تلقائيًا ما لم يتم الإلغاء قبل التجديد.", "**لا يوجد استرداد.** باستثناء ما يقتضيه القانون الإلزامي، **جميع المدفوعات نهائية وغير قابلة للاسترداد، بما في ذلك أي فترة فوترة بدأت بالفعل أو وقت غير مستخدم أو تجديدات غير مقصودة**. فترات التجربة (إن وُجدت) تتحول تلقائيًا إلى اشتراك مدفوع.", "**أنت مسؤول عن إلغاء اشتراكك** مباشرةً مع مزود الفوترة: Apple (الإعدادات → اسمك → الاشتراكات)، Google (متجر Play → المدفوعات والاشتراكات)، Stripe (بوابة العميل أو support@innfeel.app).", "حذف حسابك على InnFeel **لا يُلغي** الاشتراك المُفوتر من Apple أو Google أو Stripe — ألغه بشكل منفصل. لن يتم إصدار أي استرداد عن الفترات المدفوعة.", "الاتحاد الأوروبي/المملكة المتحدة: بالاشتراك تطلب صراحةً التنفيذ الفوري للمحتوى الرقمي وتتنازل، في الحدود المسموح بها، عن حق الانسحاب لمدة 14 يومًا."] },
      { h: "6. التغييرات على الخدمة والأسعار", body: ["قد نضيف أو نعدل أو نزيل ميزات ونغير الأسعار. تسري تغييرات الأسعار من دورة التجديد التالية ويتم الإخطار بها عند الاقتضاء."] },
      { h: "7. الإنهاء", body: ["يمكنك حذف حسابك في أي وقت من الإعدادات → الحساب. يمكننا تعليق أو إنهاء الوصول فورًا عند المخالفة أو المخاطر أو الأسباب المشروعة."] },
      { h: "8. إخلاء المسؤولية", body: ["يُقدم InnFeel \"كما هو\". إلى أقصى حد يسمح به القانون، نُخلي مسؤوليتنا عن جميع الضمانات. InnFeel **ليس جهازًا طبيًا** ولا يقدم نصيحة طبية. في حالة الأزمة، اتصل بخدمات الطوارئ المحلية."] },
      { h: "9. حد المسؤولية", body: ["إلى أقصى حد يسمح به القانون، لن نكون مسؤولين عن أي أضرار غير مباشرة أو عرضية أو خاصة أو تبعية أو عقابية. تقتصر مسؤوليتنا الإجمالية على الأكبر من المبلغ المدفوع خلال 12 شهرًا أو 50 دولارًا أمريكيًا."] },
      { h: "10. التعويض", body: ["توافق على الدفاع عنا وتعويضنا عن أي مطالبات ناشئة عن محتواك أو استخدامك للخدمة أو انتهاكك لهذه الشروط."] },
      { h: "11. خدمات الطرف الثالث", body: ["نحن ندمج أطرافًا ثالثة (IAP من Apple/Google، Stripe، RevenueCat، Apple Music، Spotify، Expo Push، مزودو الذكاء الاصطناعي). تنطبق شروطهم على أجزائهم."] },
      { h: "12. القانون المطبق", body: ["تخضع هذه الشروط لقوانين بلد مقرنا الرئيسي، دون المساس بالقوانين الاستهلاكية الإلزامية في اختصاصك."] },
      { h: "13. شروط Apple / Google الإضافية", body: ["إذا حملت التطبيق من Apple أو Google، فإن هذه الشروط بينك وبيننا وليس المنصة. Apple وGoogle مستفيدان ثانويان."] },
      { h: "14. تغييرات الشروط", body: ["قد نحدّثها. يتم الإخطار بالتغييرات الجوهرية في التطبيق. الاستخدام المستمر يعني القبول."] },
    ],
    contactIntro: "أسئلة؟ البريد الإلكتروني",
    contactEmail: "support@innfeel.app",
  },
};

// --------------------- PRIVACY POLICY ---------------------
const PRIVACY: Record<LocaleCode, LegalDoc> = {
  en: {
    title: "InnFeel — Privacy Policy",
    effective: "Effective date: " + EFFECTIVE_DATE,
    intro: "This Privacy Policy explains what personal data InnFeel (\"we\") collects, why, how we use and share it, and the rights you have. It applies to everyone using the InnFeel app worldwide and complies with GDPR, UK GDPR, CCPA/CPRA, LGPD, PIPEDA, and equivalent laws.",
    sections: [
      { h: "1. Data controller", body: ["InnFeel is the controller. Contact: support@innfeel.app."] },
      { h: "2. What we collect", body: ["• **Account data**: name, email, hashed password, avatar, creation date.", "• **Auras & interactions**: emotion, word, intensity, optional photo/video/audio, text, music reference, privacy setting, reactions, comments, friendships, messages.", "• **Device & technical data**: push token, platform, language, app version, crash diagnostics.", "• **Subscription data**: status and expiry from Apple/Google/Stripe/RevenueCat. We do not store your full card number.", "• **Minimal usage analytics**: streaks, aggregated feature usage. No cross-app tracking."] },
      { h: "3. Why we use it (GDPR legal bases)", body: ["• **To provide the Service** (contract): authenticate, store auras, deliver messages, generate stats.", "• **To personalise wellness insights** (contract): a short daily sentence via an AI provider based on your emotion (no name/email/identifier sent to the AI).", "• **To send notifications** (legitimate interest/consent): reminders, reactions, comments, messages, friend activity. Any category can be disabled in Settings.", "• **To process payments** (contract): via Apple IAP, Google Play Billing, Stripe, RevenueCat.", "• **To secure and improve the Service** (legitimate interest / legal obligation): abuse prevention, fraud detection."] },
      { h: "4. Who we share data with", body: ["• Your friends — only data you choose to share.", "• Processors: MongoDB Atlas, cloud provider, Expo (push), Apple/Google/Stripe/RevenueCat, AI provider, iTunes & Spotify search, email sender (Resend/SendGrid).", "• Authorities: only on valid legal process.", "**We do NOT sell your personal data.**"] },
      { h: "5. International transfers", body: ["If data leaves your country we rely on Standard Contractual Clauses or equivalent safeguards."] },
      { h: "6. Retention", body: ["• Account: while active.", "• Auras/messages: until you delete them or your account.", "• After deletion: erased, except 30-day backups and records we must keep by law."] },
      { h: "7. Your rights", body: ["Depending on your country: access, rectify, erase, restrict, object, port, withdraw consent, lodge a complaint. California: right to know, delete, correct, opt-out of sale/sharing (we don't sell), non-discrimination. Use Settings → Account or email support@innfeel.app. Response within 30 days."] },
      { h: "8. Security", body: ["TLS in transit, bcrypt for passwords, limited access, regular updates. No system is 100% secure; use a strong unique password."] },
      { h: "9. Children", body: ["Not directed to children under 13 (or 16 in EEA/UK). We do not knowingly collect their data. Contact support@innfeel.app to report."] },
      { h: "10. Cookies & similar tech", body: ["Essential device storage for tokens and preferences. No ad cookies, no cross-site trackers."] },
      { h: "11. Changes", body: ["Material changes are notified in-app. The effective date reflects the last update."] },
      { h: "12. Contact & complaints", body: ["support@innfeel.app. EEA users may also contact their local Data Protection Authority."] },
    ],
    contactIntro: "Questions or complaints?",
    contactEmail: "support@innfeel.app",
  },
  fr: {
    title: "InnFeel — Politique de Confidentialité",
    effective: "Date d'effet : 1er juin 2025",
    intro: "Cette Politique explique quelles données personnelles InnFeel (« nous ») collecte, pourquoi, comment nous les utilisons et partageons, et vos droits. Elle s'applique mondialement et respecte le RGPD, le RGPD UK, le CCPA/CPRA, la LGPD, la PIPEDA et lois équivalentes.",
    sections: [
      { h: "1. Responsable de traitement", body: ["InnFeel est le responsable. Contact : support@innfeel.app."] },
      { h: "2. Ce que nous collectons", body: ["• **Données de compte** : nom, email, mot de passe haché, avatar, date de création.", "• **Auras et interactions** : émotion, mot, intensité, photo/vidéo/audio optionnels, texte, référence musique, confidentialité, réactions, commentaires, amitiés, messages.", "• **Données techniques** : token push, plateforme, langue, version de l'app, diagnostics de crash.", "• **Données d'abonnement** : statut et expiration depuis Apple/Google/Stripe/RevenueCat. Nous ne stockons pas votre numéro de carte complet.", "• **Analytique minimale** : streaks, usage agrégé. Pas de tracking inter-apps."] },
      { h: "3. Pourquoi (bases légales RGPD)", body: ["• **Fournir le Service** (contrat) : authentification, stockage des auras, messages, stats.", "• **Personnaliser les insights bien-être** (contrat) : phrase quotidienne via IA basée sur votre émotion (aucun nom/email/identifiant envoyé à l'IA).", "• **Envoyer des notifications** (intérêt légitime/consentement) : rappels, réactions, commentaires, messages, activité amis. Désactivable dans les Paramètres.", "• **Traiter les paiements** (contrat) : via IAP Apple, Google Play, Stripe, RevenueCat.", "• **Sécuriser et améliorer le Service** (intérêt légitime/obligation légale) : prévention abus et fraude."] },
      { h: "4. Avec qui nous partageons", body: ["• Vos amis — uniquement les données que vous partagez.", "• Sous-traitants : MongoDB Atlas, hébergeur cloud, Expo (push), Apple/Google/Stripe/RevenueCat, fournisseur IA, iTunes & Spotify Search, émetteur email (Resend/SendGrid).", "• Autorités : uniquement sur demande légale valide.", "**Nous NE vendons PAS vos données personnelles.**"] },
      { h: "5. Transferts internationaux", body: ["Si des données quittent votre pays, nous utilisons les Clauses Contractuelles Types ou garanties équivalentes."] },
      { h: "6. Durée de conservation", body: ["• Compte : tant qu'il est actif.", "• Auras/messages : jusqu'à suppression par vous.", "• Après suppression : effacement, sauf sauvegardes 30 jours et registres légaux obligatoires."] },
      { h: "7. Vos droits", body: ["Selon votre pays : accès, rectification, effacement, limitation, opposition, portabilité, retrait du consentement, réclamation. Californie : droits de savoir, supprimer, corriger, opt-out vente/partage (nous ne vendons pas), non-discrimination. Utilisez Paramètres → Compte ou email support@innfeel.app. Réponse sous 30 jours."] },
      { h: "8. Sécurité", body: ["TLS en transit, bcrypt pour les mots de passe, accès restreint, mises à jour régulières. Aucun système n'est 100% sûr ; utilisez un mot de passe fort et unique."] },
      { h: "9. Enfants", body: ["InnFeel n'est pas destiné aux moins de 13 ans (16 dans l'EEE/RU). Nous ne collectons pas sciemment leurs données. Contactez support@innfeel.app pour signaler."] },
      { h: "10. Cookies et technologies similaires", body: ["Stockage essentiel pour tokens et préférences. Pas de cookies publicitaires ni de traceurs inter-sites."] },
      { h: "11. Modifications", body: ["Les modifications importantes sont notifiées dans l'app. La date d'effet reflète la dernière mise à jour."] },
      { h: "12. Contact et plaintes", body: ["support@innfeel.app. Les utilisateurs UE peuvent aussi contacter leur autorité de protection des données (en France, la CNIL)."] },
    ],
    contactIntro: "Questions ou plaintes ?",
    contactEmail: "support@innfeel.app",
  },
  es: {
    title: "InnFeel — Política de Privacidad",
    effective: "Fecha de vigencia: 1 de junio de 2025",
    intro: "Esta Política explica qué datos personales recopila InnFeel (\"nosotros\"), por qué, cómo los usamos y compartimos, y tus derechos. Aplica a todos los usuarios y cumple con RGPD, UK GDPR, CCPA/CPRA, LGPD, PIPEDA y leyes equivalentes.",
    sections: [
      { h: "1. Responsable del tratamiento", body: ["InnFeel es el responsable. Contacto: support@innfeel.app."] },
      { h: "2. Qué recopilamos", body: ["• **Datos de cuenta**: nombre, email, contraseña hasheada, avatar, fecha de creación.", "• **Auras e interacciones**: emoción, palabra, intensidad, foto/vídeo/audio opcional, texto, música, privacidad, reacciones, comentarios, amistades, mensajes.", "• **Datos técnicos**: token push, plataforma, idioma, versión, diagnósticos.", "• **Datos de suscripción**: estado y caducidad desde Apple/Google/Stripe/RevenueCat. No guardamos tu número de tarjeta completo.", "• **Analítica mínima**: rachas, uso agregado. Sin tracking entre apps."] },
      { h: "3. Por qué (bases legales RGPD)", body: ["• **Prestar el Servicio** (contrato).", "• **Personalizar insights de bienestar** (contrato): frase diaria vía IA basada en tu emoción (sin nombre/email enviados).", "• **Enviar notificaciones** (interés legítimo/consentimiento): desactivables en Ajustes.", "• **Procesar pagos** (contrato): vía IAP Apple, Google Play, Stripe, RevenueCat.", "• **Seguridad y mejora** (interés legítimo/obligación legal)."] },
      { h: "4. Con quién compartimos", body: ["• Tus amigos — solo lo que eliges compartir.", "• Encargados: MongoDB Atlas, proveedor cloud, Expo, Apple/Google/Stripe/RevenueCat, IA, iTunes & Spotify Search, email (Resend).", "• Autoridades: solo con proceso legal válido.", "**NO vendemos tus datos personales.**"] },
      { h: "5. Transferencias internacionales", body: ["Usamos Cláusulas Contractuales Tipo o garantías equivalentes."] },
      { h: "6. Conservación", body: ["• Cuenta: mientras esté activa.", "• Auras/mensajes: hasta que los borres.", "• Tras eliminación: borrado, salvo backups 30 días y obligaciones legales."] },
      { h: "7. Tus derechos", body: ["Acceso, rectificación, supresión, limitación, oposición, portabilidad, retirada de consentimiento, reclamación. California: derechos de saber, borrar, corregir, opt-out venta (no vendemos), no discriminación. Usa Ajustes → Cuenta o support@innfeel.app. Respuesta en 30 días."] },
      { h: "8. Seguridad", body: ["TLS, bcrypt, acceso restringido, actualizaciones regulares."] },
      { h: "9. Menores", body: ["No dirigido a menores de 13 (16 EEE/RU). No recopilamos sus datos a sabiendas."] },
      { h: "10. Cookies y similares", body: ["Almacenamiento esencial para tokens y preferencias. Sin cookies publicitarias."] },
      { h: "11. Cambios", body: ["Cambios importantes notificados en la app."] },
      { h: "12. Contacto", body: ["support@innfeel.app. Usuarios UE pueden contactar a su autoridad de protección de datos (AEPD en España)."] },
    ],
    contactIntro: "¿Preguntas o reclamaciones?",
    contactEmail: "support@innfeel.app",
  },
  it: {
    title: "InnFeel — Informativa sulla Privacy",
    effective: "Data di efficacia: 1 giugno 2025",
    intro: "Questa Informativa spiega quali dati personali raccoglie InnFeel (\"noi\"), perché, come li usiamo e condividiamo, e i tuoi diritti. Si applica in tutto il mondo e rispetta GDPR, UK GDPR, CCPA/CPRA, LGPD, PIPEDA e leggi equivalenti.",
    sections: [
      { h: "1. Titolare del trattamento", body: ["InnFeel è il titolare. Contatto: support@innfeel.app."] },
      { h: "2. Cosa raccogliamo", body: ["• **Dati dell'account**: nome, email, password hashed, avatar, data di creazione.", "• **Auras e interazioni**: emozione, parola, intensità, foto/video/audio opzionali, testo, musica, privacy, reazioni, commenti, amicizie, messaggi.", "• **Dati tecnici**: token push, piattaforma, lingua, versione, diagnostica.", "• **Dati di abbonamento**: stato e scadenza da Apple/Google/Stripe/RevenueCat. Non conserviamo il numero di carta completo.", "• **Analitica minima**: streak, uso aggregato. Nessun tracking tra app."] },
      { h: "3. Perché (basi giuridiche GDPR)", body: ["• **Fornire il Servizio** (contratto).", "• **Personalizzare insights di benessere** (contratto): frase giornaliera via IA basata sull'emozione (senza nome/email inviati).", "• **Inviare notifiche** (legittimo interesse/consenso): disattivabili dalle Impostazioni.", "• **Elaborare pagamenti** (contratto): via IAP Apple, Google Play, Stripe, RevenueCat.", "• **Sicurezza e miglioramento** (legittimo interesse/obbligo legale)."] },
      { h: "4. Con chi condividiamo", body: ["• I tuoi amici — solo ciò che scegli di condividere.", "• Responsabili: MongoDB Atlas, cloud provider, Expo, Apple/Google/Stripe/RevenueCat, IA, iTunes & Spotify Search, email (Resend).", "• Autorità: solo con processo legale valido.", "**NON vendiamo i tuoi dati personali.**"] },
      { h: "5. Trasferimenti internazionali", body: ["Usiamo Clausole Contrattuali Standard o garanzie equivalenti."] },
      { h: "6. Conservazione", body: ["• Account: mentre attivo.", "• Auras/messaggi: fino alla cancellazione.", "• Dopo cancellazione: cancellato, salvo backup 30 giorni e obblighi legali."] },
      { h: "7. I tuoi diritti", body: ["Accesso, rettifica, cancellazione, limitazione, opposizione, portabilità, revoca consenso, reclamo. California: diritti di sapere, cancellare, correggere, opt-out vendita (non vendiamo), non discriminazione. Usa Impostazioni → Account o support@innfeel.app. Risposta entro 30 giorni."] },
      { h: "8. Sicurezza", body: ["TLS, bcrypt, accesso limitato, aggiornamenti regolari."] },
      { h: "9. Minori", body: ["Non rivolto ai minori di 13 anni (16 in SEE/UK). Non raccogliamo consapevolmente i loro dati."] },
      { h: "10. Cookie e tecnologie simili", body: ["Archiviazione essenziale per token e preferenze. Nessun cookie pubblicitario."] },
      { h: "11. Modifiche", body: ["Modifiche importanti notificate nell'app."] },
      { h: "12. Contatto", body: ["support@innfeel.app. Utenti UE possono contattare l'autorità di protezione dati (Garante in Italia)."] },
    ],
    contactIntro: "Domande o reclami?",
    contactEmail: "support@innfeel.app",
  },
  de: {
    title: "InnFeel — Datenschutzerklärung",
    effective: "Gültigkeitsdatum: 1. Juni 2025",
    intro: "Diese Datenschutzerklärung erklärt, welche personenbezogenen Daten InnFeel („wir\") erhebt, warum, wie wir sie verwenden und weitergeben, und welche Rechte du hast. Sie gilt weltweit und entspricht DSGVO, UK GDPR, CCPA/CPRA, LGPD, PIPEDA und vergleichbaren Gesetzen.",
    sections: [
      { h: "1. Verantwortlicher", body: ["InnFeel ist der Verantwortliche. Kontakt: support@innfeel.app."] },
      { h: "2. Was wir erheben", body: ["• **Kontodaten**: Name, E-Mail, gehashtes Passwort, Avatar, Erstellungsdatum.", "• **Auren und Interaktionen**: Emotion, Wort, Intensität, optional Foto/Video/Audio, Text, Musikreferenz, Privatsphäre, Reaktionen, Kommentare, Freundschaften, Nachrichten.", "• **Technische Daten**: Push-Token, Plattform, Sprache, App-Version, Absturzdiagnose.", "• **Abonnementdaten**: Status und Ablauf von Apple/Google/Stripe/RevenueCat. Wir speichern keine vollständige Kartennummer.", "• **Minimale Nutzungsanalyse**: Streaks, aggregierte Nutzung. Kein appübergreifendes Tracking."] },
      { h: "3. Warum (DSGVO-Rechtsgrundlagen)", body: ["• **Dienst bereitstellen** (Vertrag).", "• **Wellness-Einblicke personalisieren** (Vertrag): tägliche Phrase via KI basierend auf deiner Emotion (keine Namen/E-Mails gesendet).", "• **Benachrichtigungen senden** (berechtigtes Interesse/Einwilligung): in Einstellungen deaktivierbar.", "• **Zahlungen abwickeln** (Vertrag): via Apple IAP, Google Play, Stripe, RevenueCat.", "• **Sichern und verbessern** (berechtigtes Interesse/Rechtspflicht)."] },
      { h: "4. An wen wir weitergeben", body: ["• Deine Freunde — nur was du teilst.", "• Auftragsverarbeiter: MongoDB Atlas, Cloud-Anbieter, Expo, Apple/Google/Stripe/RevenueCat, KI-Anbieter, iTunes & Spotify Search, E-Mail (Resend).", "• Behörden: nur bei gültigem Rechtsverfahren.", "**Wir verkaufen deine Daten NICHT.**"] },
      { h: "5. Internationale Übermittlungen", body: ["Wir stützen uns auf Standardvertragsklauseln oder gleichwertige Garantien."] },
      { h: "6. Aufbewahrung", body: ["• Konto: solange aktiv.", "• Auren/Nachrichten: bis zur Löschung.", "• Nach Löschung: gelöscht, außer 30-Tage-Backups und gesetzlicher Pflichten."] },
      { h: "7. Deine Rechte", body: ["Auskunft, Berichtigung, Löschung, Einschränkung, Widerspruch, Datenübertragbarkeit, Widerruf, Beschwerde. Kalifornien: Rechte auf Auskunft, Löschung, Berichtigung, Opt-out vom Verkauf (wir verkaufen nicht), Nichtdiskriminierung. Nutze Einstellungen → Konto oder support@innfeel.app. Antwort binnen 30 Tagen."] },
      { h: "8. Sicherheit", body: ["TLS, bcrypt für Passwörter, eingeschränkter Zugriff, regelmäßige Updates."] },
      { h: "9. Kinder", body: ["Nicht an Kinder unter 13 Jahren gerichtet (16 im EWR/UK). Wir erheben bewusst keine Daten von ihnen."] },
      { h: "10. Cookies und ähnliche Technologien", body: ["Essenzieller Gerätespeicher für Tokens und Einstellungen. Keine Werbecookies."] },
      { h: "11. Änderungen", body: ["Wesentliche Änderungen werden in der App angekündigt."] },
      { h: "12. Kontakt", body: ["support@innfeel.app. EU-Nutzer können auch ihre Datenschutzbehörde kontaktieren."] },
    ],
    contactIntro: "Fragen oder Beschwerden?",
    contactEmail: "support@innfeel.app",
  },
  pt: {
    title: "InnFeel — Política de Privacidade",
    effective: "Data de vigência: 1 de junho de 2025",
    intro: "Esta Política explica que dados pessoais a InnFeel (\"nós\") recolhe, porquê, como os usamos e partilhamos, e os teus direitos. Aplica-se mundialmente e cumpre o RGPD, UK GDPR, CCPA/CPRA, LGPD, PIPEDA e leis equivalentes.",
    sections: [
      { h: "1. Responsável pelo tratamento", body: ["InnFeel é o responsável. Contacto: support@innfeel.app."] },
      { h: "2. O que recolhemos", body: ["• **Dados de conta**: nome, email, palavra-passe hashed, avatar, data de criação.", "• **Auras e interações**: emoção, palavra, intensidade, foto/vídeo/áudio opcional, texto, música, privacidade, reações, comentários, amizades, mensagens.", "• **Dados técnicos**: token push, plataforma, idioma, versão, diagnósticos.", "• **Dados de subscrição**: estado e expiração via Apple/Google/Stripe/RevenueCat. Não guardamos o número de cartão completo.", "• **Analítica mínima**: sequências, uso agregado."] },
      { h: "3. Porquê (bases legais RGPD)", body: ["• **Prestar o Serviço** (contrato).", "• **Personalizar insights de bem-estar** (contrato): frase diária via IA baseada na emoção (sem nome/email enviados).", "• **Enviar notificações** (interesse legítimo/consentimento): desativáveis nas Definições.", "• **Processar pagamentos** (contrato).", "• **Segurança e melhoria** (interesse legítimo/obrigação legal)."] },
      { h: "4. Com quem partilhamos", body: ["• Teus amigos — só o que partilhas.", "• Subcontratantes: MongoDB Atlas, cloud, Expo, Apple/Google/Stripe/RevenueCat, IA, iTunes & Spotify Search, email (Resend).", "• Autoridades: apenas com processo legal válido.", "**NÃO vendemos os teus dados.**"] },
      { h: "5. Transferências internacionais", body: ["Usamos Cláusulas Contratuais-Tipo ou garantias equivalentes."] },
      { h: "6. Conservação", body: ["• Conta: enquanto ativa.", "• Auras/mensagens: até apagares.", "• Após eliminação: apagado, exceto backups 30 dias e obrigações legais."] },
      { h: "7. Teus direitos", body: ["Acesso, retificação, apagamento, limitação, oposição, portabilidade, retirada de consentimento, reclamação. Usa Definições → Conta ou support@innfeel.app. Resposta em 30 dias."] },
      { h: "8. Segurança", body: ["TLS, bcrypt, acesso restrito, atualizações regulares."] },
      { h: "9. Crianças", body: ["Não dirigido a menores de 13 anos (16 no EEE/RU)."] },
      { h: "10. Cookies e similares", body: ["Armazenamento essencial para tokens e preferências. Sem cookies publicitários."] },
      { h: "11. Alterações", body: ["Alterações importantes notificadas na app."] },
      { h: "12. Contacto", body: ["support@innfeel.app. Utilizadores UE podem contactar a sua autoridade de proteção de dados (CNPD em Portugal)."] },
    ],
    contactIntro: "Perguntas ou reclamações?",
    contactEmail: "support@innfeel.app",
  },
  ar: {
    title: "InnFeel — سياسة الخصوصية",
    effective: "تاريخ السريان: 1 يونيو 2025",
    intro: "تشرح هذه السياسة البيانات الشخصية التي تجمعها InnFeel (\"نحن\")، ولماذا، وكيف نستخدمها ونشاركها، وحقوقك. تنطبق في جميع أنحاء العالم وتتوافق مع GDPR وUK GDPR وCCPA/CPRA وLGPD وPIPEDA والقوانين المماثلة.",
    sections: [
      { h: "1. المسؤول عن البيانات", body: ["InnFeel هي المسؤولة. الاتصال: support@innfeel.app."] },
      { h: "2. ما نجمعه", body: ["• **بيانات الحساب**: الاسم، البريد، كلمة مرور مجزأة، الصورة الرمزية، تاريخ الإنشاء.", "• **الهالات والتفاعلات**: المشاعر، الكلمة، الشدة، صور/فيديو/صوت اختياري، نص، مرجع موسيقى، الخصوصية، التفاعلات، التعليقات، الصداقات، الرسائل.", "• **البيانات التقنية**: رمز الدفع، النظام، اللغة، الإصدار، تشخيصات الأعطال.", "• **بيانات الاشتراك**: الحالة والانتهاء من Apple/Google/Stripe/RevenueCat. لا نخزن رقم بطاقتك الكامل.", "• **تحليلات محدودة**: السلاسل، الاستخدام المجمع."] },
      { h: "3. لماذا (الأسس القانونية لـ GDPR)", body: ["• **تقديم الخدمة** (عقد).", "• **تخصيص رؤى العافية** (عقد): جملة يومية عبر الذكاء الاصطناعي بناءً على شعورك (لا يُرسل اسم/بريد).", "• **إرسال الإشعارات** (مصلحة مشروعة/موافقة): قابلة للتعطيل من الإعدادات.", "• **معالجة المدفوعات** (عقد).", "• **التأمين والتحسين** (مصلحة مشروعة/التزام قانوني)."] },
      { h: "4. مع من نشارك", body: ["• أصدقاؤك — فقط ما تختار مشاركته.", "• معالجو البيانات: MongoDB Atlas، مزود السحابة، Expo، Apple/Google/Stripe/RevenueCat، مزود الذكاء الاصطناعي، iTunes وSpotify Search، البريد (Resend).", "• السلطات: فقط بموجب إجراء قانوني صحيح.", "**نحن لا نبيع بياناتك الشخصية.**"] },
      { h: "5. النقل الدولي", body: ["نعتمد على البنود التعاقدية القياسية أو ضمانات مماثلة."] },
      { h: "6. مدة الاحتفاظ", body: ["• الحساب: ما دام نشطًا.", "• الهالات/الرسائل: حتى تحذفها.", "• بعد الحذف: محذوفة، باستثناء نسخ احتياطية (30 يومًا) والالتزامات القانونية."] },
      { h: "7. حقوقك", body: ["الوصول، التصحيح، المحو، التقييد، الاعتراض، النقل، سحب الموافقة، الشكوى. استخدم الإعدادات → الحساب أو support@innfeel.app. الرد خلال 30 يومًا."] },
      { h: "8. الأمان", body: ["TLS، bcrypt، وصول محدود، تحديثات منتظمة."] },
      { h: "9. الأطفال", body: ["غير موجه للأطفال دون 13 عامًا (16 في المنطقة الاقتصادية الأوروبية/المملكة المتحدة)."] },
      { h: "10. ملفات تعريف الارتباط وما شابه", body: ["تخزين جهاز أساسي للرموز والتفضيلات. لا توجد ملفات تعريف ارتباط إعلانية."] },
      { h: "11. التغييرات", body: ["يتم إعلام المستخدمين بالتغييرات الجوهرية داخل التطبيق."] },
      { h: "12. الاتصال", body: ["support@innfeel.app. يمكن لمستخدمي الاتحاد الأوروبي أيضًا الاتصال بسلطة حماية البيانات المحلية."] },
    ],
    contactIntro: "أسئلة أو شكاوى؟",
    contactEmail: "support@innfeel.app",
  },
};

export function getTerms(locale: LocaleCode): LegalDoc { return TERMS[locale] || TERMS.en; }
export function getPrivacy(locale: LocaleCode): LegalDoc { return PRIVACY[locale] || PRIVACY.en; }
