/**
 * Localized legal content — Terms of Service + Privacy Policy for InnFeel.
 *
 * The English version (en) is the canonical legal version. Other languages
 * are informational translations that ship alongside it for UX. In any
 * conflict, the English text controls (subject to mandatory local consumer
 * law in your country).
 *
 * v2.0 — June 2025
 *  • Added explicit Pro (4.99 €) and Zen (12.99 €) tier disclosure.
 *  • New Section 6 — AI features, wellness tools and user responsibility.
 *    Spells out that AI suggestions, Guided Journaling, Breathing,
 *    Meditation, Mood Pattern insights and the Aura analyses are NOT
 *    medical advice and NOT a substitute for a licensed professional.
 *    The user expressly accepts responsibility for interpreting and
 *    verifying AI outputs.
 *  • Strengthened Section 9 Disclaimers and Section 10 Liability cap.
 */

import { LocaleCode } from "./i18n";

export type LegalSection = { h: string; body: string[] }; // h = heading, body = paragraphs (markdown-lite)
export type LegalDoc = { title: string; effective: string; intro: string; sections: LegalSection[]; contactIntro: string; contactEmail: string };

export const EFFECTIVE_DATE = "June 7, 2025";

// --------------------- TERMS OF SERVICE ---------------------
const TERMS: Record<LocaleCode, LegalDoc> = {
  en: {
    title: "InnFeel — Terms of Service",
    effective: "Effective date: " + EFFECTIVE_DATE,
    intro: "These Terms of Service (\"Terms\") govern your access to and use of the InnFeel mobile application and related services (the \"Service\"), operated by InnFeel (\"we\", \"us\", \"our\"). By creating an account or using InnFeel, you agree to these Terms. If you do not agree, do not use the Service.",
    sections: [
      { h: "1. Who may use InnFeel", body: ["You must be at least 13 years old (16 in the EEA/UK where required by local law) and able to form a binding contract."] },
      { h: "2. Your account", body: ["You are responsible for keeping your credentials confidential and for all activity under your account. You must provide accurate information. Notify us at support@innfeel.app of any unauthorised use."] },
      { h: "3. User content", body: ["You retain ownership of the auras, photos, videos, text, audio notes, journal entries and other content you submit (\"User Content\"). By submitting User Content you grant us a worldwide, non-exclusive, royalty-free, sub-licensable licence to host, store, reproduce, display, adapt and distribute it solely to operate, improve and secure the Service. This licence ends when you delete the content or your account, except for: backups retained up to 30 days, content already shared with friends, and where retention is required by law.", "You are solely responsible for your User Content. You must not post anything unlawful, defamatory, harassing, sexually explicit involving minors, infringing, or hateful. We may remove content and suspend accounts to enforce these Terms or applicable law."] },
      { h: "4. Acceptable use", body: ["You must not: reverse-engineer or scrape the Service; circumvent security or reciprocity rules; impersonate anyone; spam or harass; introduce malware; resell the Service without our written permission; abuse AI features to generate harmful, illegal or deceptive content."] },
      { h: "5. Plans, subscriptions, billing and no-refund policy", body: [
        "InnFeel offers three plans: a **Free** plan, a **Pro** subscription and a **Zen** subscription. Indicative reference prices in the Eurozone are **Pro 4.99 €/month** and **Zen 12.99 €/month**, taxes included where applicable. Local pricing, currency and any introductory offers are shown in-app at checkout and always prevail.",
        "Each plan unlocks a different quota and set of features (notably: daily AI credits — currently 5/day for Pro and 20/day for Zen, shared across the AI Coach and Guided Journaling; access to Guided Meditation themes; Breathing rituals; Streak Freeze use; HD Aura reels; Close Friends; etc.). Daily AI quotas reset each calendar day in your timezone — **unused credits do not roll over**. We may adjust quotas to keep the Service stable and sustainable; material reductions will be notified.",
        "Pro and Zen are billed recurrently via the Apple App Store or Google Play. Subscriptions renew automatically at the end of each period unless cancelled before renewal. Streak Freeze bundles, music add-ons and other one-time purchases are non-refundable digital goods consumed on use.",
        "**No refunds.** Except where required by mandatory applicable law, **all payments are final and non-refundable, including for any billing period already started, unused time, accidental renewals, downgrades or unused AI credits**. Free trial periods (if offered) convert into paid subscriptions automatically unless cancelled before the trial ends.",
        "**You are responsible for cancelling your subscription** directly with the billing provider: Apple (Settings → your name → Subscriptions → InnFeel) or Google (Play Store → Payments & subscriptions). Tier upgrades take effect immediately and tier downgrades at the next billing cycle.",
        "Deleting your InnFeel account does **not** cancel a subscription billed by Apple or Google — cancel it with the provider separately. We cannot issue refunds for periods already paid.",
        "EU/UK: by subscribing or purchasing digital content you expressly request immediate performance and waive your 14-day withdrawal right to the extent permitted.",
      ] },
      { h: "6. AI features, wellness tools and your responsibility", body: [
        "InnFeel includes AI-powered features (the \"AI Wellness Coach\" powered by Anthropic Claude Sonnet 4.5; AI-assisted Guided Journaling; daily AI insights; voice transcription; Aura, mood and pattern analyses) as well as guided wellness rituals (Breathing exercises, Guided Meditation, Streak Freeze, gamification, leaderboards). These features are intended for **emotional self-reflection, journaling and entertainment only**.",
        "**You acknowledge, understand and accept that:** (a) AI outputs are generated automatically by third-party language models and may be **incorrect, inaccurate, biased, outdated, hallucinated, inappropriate, or harmful**; (b) **you are solely responsible** for reading, evaluating, interpreting and verifying any AI suggestion or output before acting on it, and you must use your own judgment and, where in doubt, consult a qualified professional; (c) InnFeel **does not provide and is not responsible for** any decision, action, omission, harm, loss or consequence resulting from your reliance on AI outputs or wellness rituals; (d) AI outputs are **not personalised medical, psychological, psychiatric, legal, financial or therapeutic advice**, even when phrased as if they were.",
        "**InnFeel and its tools (AI Wellness Coach, Breathing, Guided Meditation, Guided Journaling, Aura / mood analytics, Mood Pattern insights, etc.) are NOT a substitute for**: a licensed physician, psychiatrist, psychologist, psychotherapist, counsellor, nutritionist, social worker, crisis hotline, or any qualified mental-health, medical or emergency professional. They do not diagnose, treat, cure or prevent any disease or condition.",
        "**If you are experiencing distress, suicidal thoughts, self-harm urges, severe anxiety, panic, an addiction relapse, abuse, or any medical or psychiatric emergency, stop using InnFeel immediately and contact your local emergency services or a qualified professional.** Examples: France 15 / 112 / 3114 (suicide line); EU 112; UK 999 / Samaritans 116 123; US & Canada 911 / 988; in other countries, the equivalent national service.",
        "AI features may be **temporarily slow, unavailable, rate-limited, modified, or removed without notice**, including for safety, technical or commercial reasons. We may also moderate or block AI requests we judge unsafe.",
        "We log AI conversations and journaling content to operate the Service, ensure safety, prevent abuse, and improve quality. We do not use your private content to train third-party foundational AI models. See the Privacy Policy.",
        "**By using any AI feature or wellness ritual you give your informed consent to all of the above and confirm you are not currently relying on InnFeel for medical, psychiatric or emergency care.**",
      ] },
      { h: "7. Changes to the Service and pricing", body: ["We may add, modify or remove features (including AI quotas, plan benefits, supported integrations) and change pricing. Material price changes apply from the next renewal cycle and are notified where required by law."] },
      { h: "8. Termination", body: ["You may delete your account at any time from Settings → Account. We may suspend or terminate access immediately if you breach these Terms, create risk, abuse the AI features, or for lawful business reasons. Sections 3, 5 (no-refund), 6, 9, 10 and 11 survive termination."] },
      { h: "9. Disclaimers", body: ["InnFeel is provided \"AS IS\" and \"AS AVAILABLE\". To the maximum extent permitted by law, we disclaim all warranties, express or implied (including merchantability, fitness for a particular purpose, accuracy, reliability and non-infringement). InnFeel is **not a medical device**, does not provide medical, psychological or psychiatric advice, does not diagnose, treat, cure or prevent any condition, and is **not a substitute for a qualified professional** (see Section 6). We do not guarantee that AI outputs are accurate, safe, complete or free of bias. If you are in crisis, contact local emergency services or a qualified professional."] },
      { h: "10. Limitation of liability", body: ["To the maximum extent permitted by law, we and our affiliates, officers, employees and agents will not be liable for any indirect, incidental, special, consequential, exemplary or punitive damages, nor for any loss of profits, revenues, data, goodwill, opportunities, or for any harm resulting from your reliance on AI outputs or wellness content. Our aggregate liability for any claim arising out of or relating to the Service is limited to the greater of (a) the amount you actually paid us in the 12 months immediately preceding the event giving rise to the claim, or (b) USD 50."] },
      { h: "11. Indemnification", body: ["You agree to defend, indemnify and hold us harmless from any claim, demand, loss or expense (including reasonable legal fees) arising from your User Content, your use of the Service, your reliance on AI outputs, or your violation of these Terms or any law."] },
      { h: "12. Third-party services", body: ["The Service integrates third parties (Apple/Google IAP, RevenueCat, Apple Music, Spotify, Cloudflare R2, Expo Push, Resend, Anthropic Claude, OpenAI, and other AI providers). Their terms apply to their portions of the Service and we are not responsible for their availability, content or output."] },
      { h: "13. Governing law and disputes", body: ["These Terms are governed by the laws of the country of our principal place of business, without prejudice to mandatory consumer law in your jurisdiction. Disputes will be resolved by the competent courts of that place, except where local consumer law gives you a different forum."] },
      { h: "14. Apple / Google additional terms", body: ["If you downloaded the app from Apple or Google, these Terms are between you and us, not the platform. Apple and Google are third-party beneficiaries and may enforce these Terms. You agree to comply with the platform's usage rules."] },
      { h: "15. Changes to these Terms", body: ["We may update these Terms. Material changes will be notified in-app at least 14 days before they take effect (unless required immediately for legal/safety reasons). Continued use after the effective date constitutes acceptance."] },
    ],
    contactIntro: "Questions? Email",
    contactEmail: "support@innfeel.app",
  },

  fr: {
    title: "InnFeel — Conditions Générales d'Utilisation et de Vente",
    effective: "Date d'effet : 7 juin 2025",
    intro: "Les présentes Conditions Générales d'Utilisation et de Vente (« CGU/CGV » ou « Conditions ») régissent votre accès à l'application mobile InnFeel et aux services associés (le « Service »), exploités par InnFeel (« nous »). En créant un compte ou en utilisant InnFeel, vous acceptez ces Conditions. Si vous n'êtes pas d'accord, n'utilisez pas le Service.",
    sections: [
      { h: "1. Qui peut utiliser InnFeel", body: ["Vous devez avoir au moins 13 ans (16 dans l'EEE/RU si requis par la loi locale) et pouvoir conclure un contrat."] },
      { h: "2. Votre compte", body: ["Vous êtes responsable de la confidentialité de vos identifiants et de toute activité sur votre compte. Fournissez des informations exactes. Signalez tout usage non autorisé à support@innfeel.app."] },
      { h: "3. Vos contenus", body: ["Vous conservez la propriété de vos auras, photos, vidéos, textes, notes vocales, entrées de journal et autres contenus (« Contenus Utilisateur »). En les soumettant, vous nous accordez une licence mondiale, non exclusive, gratuite et sous-licenciable pour les héberger, stocker, reproduire, afficher, adapter et distribuer uniquement pour opérer, améliorer et sécuriser le Service. Cette licence prend fin quand vous supprimez le contenu ou votre compte, sauf sauvegardes (≤ 30 jours), contenus déjà partagés avec des amis, ou obligations légales.", "Vous êtes seul responsable de vos Contenus Utilisateur. Il est interdit de publier du contenu illégal, diffamatoire, harcelant, sexuellement explicite impliquant des mineurs, contrefaisant ou haineux. Nous pouvons supprimer du contenu et suspendre des comptes."] },
      { h: "4. Utilisation acceptable", body: ["Il est interdit de : faire de la rétro-ingénierie, scraper le Service, contourner la sécurité ou la règle de réciprocité, usurper une identité, spammer ou harceler, introduire des logiciels malveillants, revendre le Service sans autorisation écrite, abuser des fonctionnalités IA pour produire du contenu nuisible, illégal ou trompeur."] },
      { h: "5. Plans, abonnements, facturation et NON-remboursement", body: [
        "InnFeel propose trois formules : un plan **Gratuit**, un abonnement **Pro** et un abonnement **Zen**. Tarifs indicatifs en zone euro : **Pro 4,99 €/mois** et **Zen 12,99 €/mois**, taxes comprises lorsque applicables. Les prix locaux, devises et offres d'introduction affichés dans l'application au moment du paiement prévalent toujours.",
        "Chaque formule débloque un quota et un ensemble de fonctionnalités différents (notamment : crédits IA quotidiens — actuellement 5/jour pour Pro et 20/jour pour Zen, partagés entre le Coach IA et le Journal Guidé ; accès aux thèmes de Méditation Guidée ; rituels de Respiration ; usage du Streak Freeze ; reels Aura HD ; Close Friends ; etc.). Les quotas IA quotidiens sont réinitialisés chaque jour calendaire dans votre fuseau horaire — **les crédits non utilisés ne sont pas reportés**. Nous pouvons ajuster les quotas pour maintenir la stabilité et la viabilité du Service ; toute baisse importante sera notifiée.",
        "Pro et Zen sont facturés de manière récurrente via l'App Store Apple ou Google Play. Les abonnements se renouvellent automatiquement sauf résiliation avant renouvellement. Les packs Streak Freeze, modules musicaux et autres achats ponctuels sont des biens numériques non remboursables, consommés à l'usage.",
        "**Aucun remboursement.** Sauf obligation légale impérative, **tout paiement est ferme et non remboursable, y compris pour toute période de facturation déjà commencée, période non utilisée, renouvellement accidentel, rétrogradation ou crédits IA non utilisés**. Les périodes d'essai (si proposées) se convertissent automatiquement en abonnement payant sauf résiliation avant leur fin.",
        "**Vous êtes responsable de résilier votre abonnement** directement auprès du prestataire : Apple (Réglages → votre nom → Abonnements → InnFeel) ou Google (Play Store → Paiements et abonnements). Les passages à un plan supérieur prennent effet immédiatement, les rétrogradations au prochain cycle de facturation.",
        "La suppression de votre compte InnFeel **ne résilie pas** un abonnement facturé par Apple ou Google — vous devez le résilier séparément. Aucun remboursement ne sera effectué pour des périodes déjà payées.",
        "UE/RU : en souscrivant ou en achetant un contenu numérique vous demandez expressément l'exécution immédiate et renoncez, dans la mesure autorisée, à votre droit de rétractation de 14 jours.",
      ] },
      { h: "6. Fonctionnalités IA, outils bien-être et VOTRE responsabilité", body: [
        "InnFeel intègre des fonctionnalités basées sur l'IA (le « Coach Bien-être IA » propulsé par Anthropic Claude Sonnet 4.5 ; le Journal Guidé assisté par IA ; les insights quotidiens IA ; la transcription vocale ; les analyses d'Aura, d'humeur et de tendances) ainsi que des rituels guidés (exercices de Respiration, Méditation Guidée, Streak Freeze, gamification, classements). Ces fonctionnalités sont destinées **à l'introspection émotionnelle, au journaling et au divertissement uniquement**.",
        "**Vous reconnaissez, comprenez et acceptez que :** (a) les sorties de l'IA sont générées automatiquement par des modèles tiers et peuvent être **incorrectes, inexactes, biaisées, obsolètes, hallucinées, inappropriées ou nuisibles** ; (b) **vous êtes seul responsable** de lire, évaluer, interpréter et vérifier toute suggestion ou sortie de l'IA avant d'agir, en utilisant votre propre jugement et, en cas de doute, en consultant un professionnel qualifié ; (c) InnFeel **ne fournit pas et n'est pas responsable de** toute décision, action, omission, dommage, perte ou conséquence résultant de votre confiance dans les sorties IA ou les rituels bien-être ; (d) les sorties de l'IA **ne constituent pas un avis médical, psychologique, psychiatrique, juridique, financier ou thérapeutique personnalisé**, même lorsqu'elles sont formulées comme tel.",
        "**InnFeel et ses outils (Coach IA, Respiration, Méditation Guidée, Journal Guidé, analyses d'Aura/humeur, insights de tendances émotionnelles, etc.) NE remplacent PAS** : un médecin, psychiatre, psychologue, psychothérapeute, conseiller, nutritionniste, travailleur social, ligne d'écoute en cas de crise, ou tout professionnel qualifié de la santé mentale, médicale ou d'urgence. Ils ne posent aucun diagnostic, ne traitent, ne soignent et ne préviennent aucune maladie ou affection.",
        "**Si vous traversez une détresse, des pensées suicidaires, des envies d'automutilation, une anxiété sévère, une crise de panique, une rechute addictive, une situation d'abus, ou toute urgence médicale ou psychiatrique, cessez immédiatement d'utiliser InnFeel et contactez les services d'urgence ou un professionnel qualifié.** Exemples : France 15 / 112 / 3114 (numéro national de prévention du suicide) ; UE 112 ; RU 999 / Samaritans 116 123 ; États-Unis & Canada 911 / 988 ; dans les autres pays, le service national équivalent.",
        "Les fonctionnalités IA peuvent être **temporairement lentes, indisponibles, limitées en débit, modifiées ou retirées sans préavis**, y compris pour des raisons de sécurité, techniques ou commerciales. Nous pouvons modérer ou bloquer des requêtes IA jugées non sûres.",
        "Nous journalisons les conversations IA et les contenus du journal pour opérer le Service, garantir la sécurité, prévenir les abus et améliorer la qualité. Nous n'utilisons pas vos contenus privés pour entraîner les modèles d'IA fondamentaux tiers. Voir la Politique de Confidentialité.",
        "**En utilisant toute fonctionnalité IA ou rituel bien-être, vous donnez votre consentement éclairé à tout ce qui précède et confirmez ne pas vous reposer sur InnFeel pour des soins médicaux, psychiatriques ou d'urgence.**",
      ] },
      { h: "7. Modifications du Service et des prix", body: ["Nous pouvons ajouter, modifier ou retirer des fonctionnalités (y compris quotas IA, avantages des plans, intégrations) et modifier les prix. Les changements de prix importants s'appliquent au prochain cycle de renouvellement et sont notifiés si la loi l'exige."] },
      { h: "8. Résiliation", body: ["Vous pouvez supprimer votre compte à tout moment depuis Paramètres → Compte. Nous pouvons suspendre ou résilier immédiatement en cas de violation, risque, abus des fonctionnalités IA ou motifs légitimes. Les sections 3, 5 (non-remboursement), 6, 9, 10 et 11 survivent à la résiliation."] },
      { h: "9. Garanties", body: ["InnFeel est fourni « EN L'ÉTAT » et « SELON DISPONIBILITÉ ». Dans la mesure maximale permise, nous déclinons toute garantie expresse ou implicite (qualité marchande, adéquation à un usage particulier, exactitude, fiabilité, absence de contrefaçon). InnFeel **n'est pas un dispositif médical**, ne fournit pas d'avis médical, psychologique ou psychiatrique, ne pose aucun diagnostic ni traitement et **ne se substitue pas à un professionnel qualifié** (voir Section 6). Nous ne garantissons pas que les sorties de l'IA soient exactes, sûres, complètes ou exemptes de biais. En cas de crise, contactez les services d'urgence ou un professionnel qualifié."] },
      { h: "10. Limitation de responsabilité", body: ["Dans la mesure maximale permise par la loi, nous, nos affiliés, dirigeants, employés et agents ne serons pas responsables des dommages indirects, incidents, spéciaux, consécutifs, exemplaires ou punitifs, ni d'aucune perte de profits, revenus, données, réputation, opportunités, ni d'aucun préjudice résultant de votre confiance dans les sorties IA ou contenus bien-être. Notre responsabilité globale pour toute réclamation est limitée au plus élevé de (a) la somme effectivement payée dans les 12 mois précédant l'événement, ou (b) 50 USD."] },
      { h: "11. Indemnisation", body: ["Vous acceptez de nous défendre, indemniser et dégager de toute responsabilité face à toute réclamation, demande, perte ou frais (y compris frais juridiques raisonnables) liés à vos Contenus, votre usage du Service, votre confiance dans les sorties IA, ou votre violation des Conditions ou de la loi."] },
      { h: "12. Services tiers", body: ["Le Service intègre des tiers (IAP Apple/Google, RevenueCat, Apple Music, Spotify, Cloudflare R2, Expo Push, Resend, Anthropic Claude, OpenAI et autres fournisseurs IA). Leurs conditions s'appliquent à leurs parties et nous ne sommes pas responsables de leur disponibilité, contenu ou sortie."] },
      { h: "13. Droit applicable et litiges", body: ["Les présentes Conditions sont régies par le droit du pays de notre principal établissement, sans préjudice des lois consommateurs impératives de votre juridiction. Les litiges seront tranchés par les juridictions compétentes de ce lieu, sauf si la loi consommateur locale vous accorde un autre forum."] },
      { h: "14. Conditions Apple / Google additionnelles", body: ["Si vous avez téléchargé l'app chez Apple ou Google, ces Conditions lient vous et nous, pas la plateforme. Apple et Google sont bénéficiaires tiers et peuvent les faire respecter. Vous acceptez de respecter les règles d'usage de la plateforme."] },
      { h: "15. Modifications des Conditions", body: ["Nous pouvons mettre à jour ces Conditions. Les modifications importantes sont notifiées dans l'app au moins 14 jours avant leur entrée en vigueur (sauf application immédiate requise pour des raisons légales/de sécurité). L'utilisation continue après la date d'effet vaut acceptation."] },
    ],
    contactIntro: "Questions ? Email",
    contactEmail: "support@innfeel.app",
  },

  es: {
    title: "InnFeel — Términos de Servicio",
    effective: "Fecha de vigencia: 7 de junio de 2025",
    intro: "Estos Términos rigen tu acceso y uso de la aplicación InnFeel y servicios relacionados (el \"Servicio\"), operado por InnFeel (\"nosotros\"). Al crear una cuenta o usar InnFeel, aceptas estos Términos. Si no aceptas, no uses el Servicio.",
    sections: [
      { h: "1. Quién puede usar InnFeel", body: ["Debes tener al menos 13 años (16 en EEE/RU) y poder celebrar un contrato vinculante."] },
      { h: "2. Tu cuenta", body: ["Eres responsable de la confidencialidad de tus credenciales y de toda actividad bajo tu cuenta. Informa de usos no autorizados a support@innfeel.app."] },
      { h: "3. Contenido del usuario", body: ["Conservas la propiedad de tus auras, fotos, vídeos, textos, notas de audio, entradas de diario y demás contenido. Al enviarlo, nos concedes una licencia mundial, no exclusiva, gratuita y sublicenciable para alojarlo, reproducirlo, mostrarlo, adaptarlo y distribuirlo únicamente para operar, mejorar y asegurar el Servicio. Esta licencia termina cuando borres el contenido o tu cuenta, salvo copias de seguridad (≤ 30 días), contenido ya compartido y obligaciones legales.", "Eres responsable de tu contenido. Está prohibido publicar contenido ilegal, difamatorio, acosador, sexualmente explícito con menores, infractor u odioso. Podemos eliminarlo y suspender cuentas."] },
      { h: "4. Uso aceptable", body: ["No debes: hacer ingeniería inversa, scraping, eludir la seguridad o reciprocidad, suplantar identidad, spam/acoso, introducir malware, revender el Servicio sin permiso, abusar de las funciones de IA para generar contenido dañino, ilegal o engañoso."] },
      { h: "5. Planes, suscripciones, facturación y política de NO reembolso", body: [
        "InnFeel ofrece tres planes: **Gratis**, suscripción **Pro** y suscripción **Zen**. Precios indicativos en la zona euro: **Pro 4,99 €/mes** y **Zen 12,99 €/mes**, impuestos incluidos cuando proceda. Los precios locales, divisas y ofertas mostrados en la app al pagar siempre prevalecen.",
        "Cada plan desbloquea cuotas y funciones distintas (entre otras: créditos IA diarios — actualmente 5/día Pro y 20/día Zen, compartidos entre Coach IA y Diario Guiado; temas de Meditación Guiada; rituales de Respiración; uso de Streak Freeze; reels HD; Close Friends; etc.). Las cuotas de IA se reinician cada día calendario en tu zona horaria — **los créditos no usados no se acumulan**. Podemos ajustar las cuotas para mantener el Servicio estable y sostenible; cualquier reducción importante será notificada.",
        "Pro y Zen se facturan recurrentemente vía App Store Apple o Google Play. Las suscripciones se renuevan automáticamente salvo cancelación previa. Los packs Streak Freeze, módulos de música y otras compras únicas son bienes digitales no reembolsables consumidos al usarse.",
        "**Sin reembolsos.** Salvo donde la ley imperativa lo exija, **todos los pagos son finales y no reembolsables, incluido cualquier período ya iniciado, tiempo no usado, renovaciones accidentales, descensos de plan o créditos IA no utilizados**. Los períodos de prueba se convierten automáticamente en suscripción pagada salvo cancelación previa.",
        "**Eres responsable de cancelar tu suscripción** directamente con el proveedor: Apple o Google. Los ascensos de plan tienen efecto inmediato y los descensos al siguiente ciclo.",
        "Borrar tu cuenta InnFeel **no cancela** una suscripción de Apple/Google — cancélala aparte. No emitimos reembolsos por períodos pagados.",
        "UE/RU: al suscribirte solicitas la ejecución inmediata y renuncias, en la medida permitida, al derecho de desistimiento de 14 días.",
      ] },
      { h: "6. Funciones de IA, herramientas de bienestar y TU responsabilidad", body: [
        "InnFeel incluye funciones basadas en IA (el \"Coach de Bienestar IA\" con Anthropic Claude Sonnet 4.5; Diario Guiado con IA; insights diarios; transcripción de voz; análisis de Aura, ánimo y patrones) y rituales guiados (Respiración, Meditación Guiada, Streak Freeze, gamificación, clasificaciones). Están destinados **únicamente a la introspección emocional, journaling y entretenimiento**.",
        "**Reconoces, comprendes y aceptas que:** (a) las salidas de IA se generan automáticamente por modelos de terceros y pueden ser **incorrectas, inexactas, sesgadas, obsoletas, alucinadas, inapropiadas o dañinas**; (b) **eres el único responsable** de leer, evaluar, interpretar y verificar cualquier sugerencia o salida antes de actuar, usando tu propio juicio y consultando a un profesional cualificado en caso de duda; (c) InnFeel **no proporciona ni se hace responsable** de ninguna decisión, acción, omisión, daño, pérdida o consecuencia derivada de tu confianza en las salidas de IA o rituales; (d) las salidas de IA **no son consejo médico, psicológico, psiquiátrico, jurídico, financiero ni terapéutico personalizado**, aunque estén formuladas como tal.",
        "**InnFeel y sus herramientas (Coach IA, Respiración, Meditación, Diario Guiado, análisis de Aura/ánimo, insights de patrones, etc.) NO sustituyen** a un médico, psiquiatra, psicólogo, psicoterapeuta, consejero, nutricionista, trabajador social, línea de crisis o cualquier profesional cualificado de salud mental, médica o de emergencia. No diagnostican, tratan, curan ni previenen ninguna enfermedad.",
        "**Si experimentas angustia, pensamientos suicidas, autolesiones, ansiedad severa, pánico, recaída adictiva, abuso o cualquier emergencia médica o psiquiátrica, deja de usar InnFeel inmediatamente y contacta servicios de emergencia o un profesional cualificado.** Ejemplos: España 112 / 024 (suicidio); UE 112; RU 999 / Samaritans 116 123; EE.UU. & Canadá 911 / 988.",
        "Las funciones de IA pueden ser **temporalmente lentas, no disponibles, limitadas, modificadas o retiradas sin previo aviso** por razones de seguridad, técnicas o comerciales. Podemos moderar o bloquear solicitudes inseguras.",
        "Registramos conversaciones de IA y contenido del diario para operar el Servicio, garantizar la seguridad, prevenir abusos y mejorar la calidad. No usamos tu contenido privado para entrenar modelos fundacionales de IA de terceros. Ver la Política de Privacidad.",
        "**Al usar cualquier función de IA o ritual de bienestar das tu consentimiento informado a todo lo anterior y confirmas que no dependes de InnFeel para atención médica, psiquiátrica o de emergencia.**",
      ] },
      { h: "7. Cambios en el Servicio y precios", body: ["Podemos añadir, modificar o eliminar funciones (incluidas cuotas IA y beneficios de plan) y cambiar precios. Cambios importantes se aplican desde el siguiente ciclo y se notifican cuando la ley lo exige."] },
      { h: "8. Terminación", body: ["Puedes borrar tu cuenta en Ajustes → Cuenta. Podemos suspender o terminar el acceso inmediatamente por incumplimiento, riesgos, abuso de IA o causas legítimas. Las secciones 3, 5, 6, 9, 10 y 11 sobreviven a la terminación."] },
      { h: "9. Exenciones", body: ["InnFeel se proporciona \"TAL CUAL\" y \"SEGÚN DISPONIBILIDAD\". En la máxima medida permitida rechazamos todas las garantías. InnFeel **no es un dispositivo médico**, no ofrece consejo médico, psicológico ni psiquiátrico, no diagnostica ni trata, y **no sustituye a un profesional cualificado** (ver Sección 6). No garantizamos que las salidas de IA sean exactas, seguras o completas. En crisis, contacta servicios de emergencia."] },
      { h: "10. Limitación de responsabilidad", body: ["En la máxima medida permitida, no seremos responsables de daños indirectos, incidentales, especiales, consecuentes, ejemplares o punitivos, ni de pérdida de beneficios, datos, reputación, oportunidades o de cualquier daño derivado de tu confianza en las salidas de IA. Nuestra responsabilidad agregada se limita al mayor de (a) lo pagado en los 12 meses anteriores o (b) 50 USD."] },
      { h: "11. Indemnización", body: ["Aceptas defendernos e indemnizarnos frente a reclamaciones derivadas de tu Contenido, uso del Servicio, confianza en las salidas de IA o incumplimiento de estos Términos o la ley."] },
      { h: "12. Servicios de terceros", body: ["Integramos terceros (IAP Apple/Google, RevenueCat, Apple Music, Spotify, Cloudflare R2, Expo Push, Resend, Anthropic Claude, OpenAI y otros). Sus condiciones aplican a sus partes."] },
      { h: "13. Ley aplicable y conflictos", body: ["Estos Términos se rigen por la ley del país de nuestro establecimiento principal, sin perjuicio de la ley de consumidor imperativa de tu jurisdicción."] },
      { h: "14. Condiciones Apple / Google", body: ["Si descargaste la app de Apple o Google, estos Términos son entre tú y nosotros, no la plataforma. Apple y Google son beneficiarios terceros."] },
      { h: "15. Cambios en los Términos", body: ["Podemos actualizarlos. Los cambios importantes se notifican en la app con al menos 14 días de antelación (salvo aplicación inmediata por motivos legales/seguridad). El uso continuado implica aceptación."] },
    ],
    contactIntro: "¿Preguntas? Email",
    contactEmail: "support@innfeel.app",
  },

  it: {
    title: "InnFeel — Termini di Servizio",
    effective: "Data di efficacia: 7 giugno 2025",
    intro: "Questi Termini regolano il tuo accesso e uso dell'app InnFeel e dei servizi correlati (il \"Servizio\"), gestito da InnFeel (\"noi\"). Creando un account o usando InnFeel, accetti questi Termini. Se non accetti, non usare il Servizio.",
    sections: [
      { h: "1. Chi può usare InnFeel", body: ["Devi avere almeno 13 anni (16 in SEE/Regno Unito se richiesto) e capacità di contrarre."] },
      { h: "2. Il tuo account", body: ["Sei responsabile della riservatezza delle credenziali e di tutte le attività sul tuo account. Segnala usi non autorizzati a support@innfeel.app."] },
      { h: "3. Contenuti utente", body: ["Mantieni la proprietà dei tuoi auras, foto, video, testi, note audio, voci di diario e altri contenuti. Inviandoli ci concedi una licenza mondiale, non esclusiva, gratuita e sublicenziabile per ospitarli, riprodurli, visualizzarli, adattarli e distribuirli solo per operare, migliorare e proteggere il Servizio. Termina alla cancellazione, salvo backup (≤ 30 giorni), contenuti già condivisi e obblighi di legge.", "Sei l'unico responsabile dei tuoi contenuti. Vietato pubblicare contenuti illegali, diffamatori, molesti, sessualmente espliciti con minori, contraffatti o d'odio."] },
      { h: "4. Uso accettabile", body: ["Vietato: reverse-engineering, scraping, aggirare la sicurezza o la reciprocità, impersonare altri, spam/molestie, introdurre malware, rivendere il Servizio, abusare delle funzioni IA per produrre contenuti dannosi, illegali o ingannevoli."] },
      { h: "5. Piani, abbonamenti, fatturazione e politica di NON rimborso", body: [
        "InnFeel offre tre piani: **Free**, abbonamento **Pro** e abbonamento **Zen**. Prezzi indicativi area euro: **Pro 4,99 €/mese** e **Zen 12,99 €/mese**, IVA inclusa ove applicabile. I prezzi locali, valute e offerte mostrati in app al checkout prevalgono sempre.",
        "Ogni piano sblocca quote e funzionalità diverse (in particolare: crediti IA giornalieri — attualmente 5/giorno Pro e 20/giorno Zen, condivisi tra Coach IA e Diario Guidato; temi di Meditazione Guidata; rituali di Respiro; uso Streak Freeze; reels HD; Close Friends; ecc.). Le quote IA si azzerano ogni giorno solare nel tuo fuso orario — **i crediti non usati non si accumulano**. Possiamo modificare le quote per mantenere il Servizio stabile e sostenibile; riduzioni rilevanti saranno notificate.",
        "Pro e Zen sono fatturati ricorrentemente tramite App Store Apple o Google Play. Rinnovo automatico salvo disdetta. I pacchetti Streak Freeze, moduli musicali e altri acquisti una tantum sono beni digitali non rimborsabili consumati all'uso.",
        "**Nessun rimborso.** Salvo legge imperativa, **tutti i pagamenti sono definitivi e non rimborsabili, inclusi periodi già iniziati, tempo non usato, rinnovi accidentali, downgrade o crediti IA non usati**. I periodi di prova si convertono automaticamente in abbonamento.",
        "**Sei responsabile della disdetta** direttamente col fornitore (Apple/Google). Upgrade immediati, downgrade al ciclo successivo.",
        "Cancellare l'account InnFeel **non annulla** un abbonamento di Apple/Google — annullalo a parte. Niente rimborsi per periodi pagati.",
        "UE/UK: sottoscrivendo richiedi l'esecuzione immediata e rinunci, nei limiti consentiti, al diritto di recesso di 14 giorni.",
      ] },
      { h: "6. Funzioni IA, strumenti di benessere e TUA responsabilità", body: [
        "InnFeel include funzioni basate su IA (il \"Wellness Coach IA\" con Anthropic Claude Sonnet 4.5; Diario Guidato con IA; insights giornalieri; trascrizione vocale; analisi di Aura, umore e pattern) e rituali guidati (Respiro, Meditazione, Streak Freeze, gamification, classifiche). Sono destinati **solo a introspezione emotiva, journaling e intrattenimento**.",
        "**Riconosci, comprendi e accetti che:** (a) le uscite dell'IA sono generate automaticamente da modelli di terzi e possono essere **errate, inaccurate, distorte, obsolete, allucinate, inappropriate o dannose**; (b) **sei l'unico responsabile** di leggere, valutare, interpretare e verificare ogni suggerimento o output prima di agire, usando il tuo giudizio e, in caso di dubbio, consultando un professionista qualificato; (c) InnFeel **non fornisce e non è responsabile** di alcuna decisione, azione, omissione, danno, perdita o conseguenza derivanti dal tuo affidamento sulle uscite IA o sui rituali; (d) le uscite dell'IA **non sono consigli medici, psicologici, psichiatrici, legali, finanziari o terapeutici personalizzati**, anche se formulate in tal senso.",
        "**InnFeel e i suoi strumenti (Coach IA, Respiro, Meditazione, Diario Guidato, analisi Aura/umore, insights pattern, ecc.) NON sostituiscono** un medico, psichiatra, psicologo, psicoterapeuta, consulente, nutrizionista, assistente sociale, linea di crisi o qualsiasi professionista qualificato della salute mentale, medica o d'emergenza. Non diagnosticano, curano né prevengono malattie.",
        "**In caso di disagio, pensieri suicidi, autolesionismo, ansia grave, panico, ricaduta nelle dipendenze, abuso o qualsiasi emergenza medica o psichiatrica, smetti subito di usare InnFeel e contatta i servizi di emergenza o un professionista qualificato.** Esempi: Italia 112 / 800 86 00 22 (Telefono Amico); UE 112; UK 999 / Samaritans 116 123; USA & Canada 911 / 988.",
        "Le funzioni IA possono essere **temporaneamente lente, non disponibili, limitate, modificate o rimosse senza preavviso** per ragioni di sicurezza, tecniche o commerciali. Possiamo moderare o bloccare richieste IA non sicure.",
        "Registriamo le conversazioni IA e i contenuti del diario per operare il Servizio, garantire la sicurezza, prevenire abusi e migliorare la qualità. Non usiamo i tuoi contenuti privati per addestrare modelli IA di terzi. Vedi l'Informativa Privacy.",
        "**Usando qualsiasi funzione IA o rituale di benessere fornisci il tuo consenso informato a quanto sopra e confermi di non affidarti a InnFeel per cure mediche, psichiatriche o d'emergenza.**",
      ] },
      { h: "7. Modifiche al Servizio e ai prezzi", body: ["Possiamo aggiungere, modificare o rimuovere funzioni (incluse quote IA) e cambiare prezzi. Modifiche rilevanti dal ciclo successivo, notificate se richiesto."] },
      { h: "8. Risoluzione", body: ["Puoi eliminare l'account in qualsiasi momento. Possiamo sospendere o risolvere immediatamente in caso di violazione, rischi, abuso IA o motivi legittimi. Le sezioni 3, 5, 6, 9, 10 e 11 sopravvivono."] },
      { h: "9. Esclusioni", body: ["InnFeel è fornito \"COSÌ COM'È\" e \"SECONDO DISPONIBILITÀ\". Escludiamo tutte le garanzie nei limiti massimi consentiti. InnFeel **non è un dispositivo medico**, non fornisce consigli medici/psicologici/psichiatrici, non diagnostica né cura, e **non sostituisce un professionista qualificato** (Sez. 6). Non garantiamo accuratezza/sicurezza/completezza delle uscite IA. In crisi: contatta servizi d'emergenza."] },
      { h: "10. Limitazione di responsabilità", body: ["Nei limiti massimi consentiti, non saremo responsabili per danni indiretti, accidentali, speciali, consequenziali, esemplari o punitivi, né per perdita di profitti, dati, reputazione, opportunità o danni derivanti dal tuo affidamento sulle uscite IA. Responsabilità totale limitata al maggiore tra (a) quanto pagato negli ultimi 12 mesi o (b) 50 USD."] },
      { h: "11. Indennizzo", body: ["Accetti di difenderci e tenerci indenni da reclami derivanti dai tuoi contenuti, uso del Servizio, affidamento sulle uscite IA o violazione di questi Termini."] },
      { h: "12. Servizi di terzi", body: ["Integriamo terzi (IAP Apple/Google, RevenueCat, Apple Music, Spotify, Cloudflare R2, Expo Push, Resend, Anthropic Claude, OpenAI e altri). I loro termini si applicano."] },
      { h: "13. Legge applicabile e controversie", body: ["Termini regolati dalla legge del paese della nostra sede principale, salvo leggi consumeristiche imperative del tuo paese."] },
      { h: "14. Condizioni Apple / Google", body: ["Se hai scaricato l'app da Apple o Google, questi Termini sono tra te e noi, non la piattaforma. Apple e Google sono beneficiari terzi."] },
      { h: "15. Modifiche ai Termini", body: ["Possiamo aggiornarli. Le modifiche importanti notificate nell'app con almeno 14 giorni di anticipo. L'uso continuato vale accettazione."] },
    ],
    contactIntro: "Domande? Email",
    contactEmail: "support@innfeel.app",
  },

  de: {
    title: "InnFeel — Nutzungsbedingungen",
    effective: "Gültigkeitsdatum: 7. Juni 2025",
    intro: "Diese Nutzungsbedingungen regeln deinen Zugang zur InnFeel-App und den zugehörigen Diensten (der „Dienst\"), betrieben von InnFeel („wir\"). Durch Anmeldung oder Nutzung akzeptierst du diese Bedingungen. Wenn du nicht zustimmst, nutze den Dienst nicht.",
    sections: [
      { h: "1. Wer InnFeel nutzen darf", body: ["Du musst mindestens 13 Jahre alt sein (16 im EWR/UK, wo erforderlich) und einen Vertrag abschließen können."] },
      { h: "2. Dein Konto", body: ["Du bist für die Vertraulichkeit deiner Zugangsdaten und alle Aktivitäten in deinem Konto verantwortlich. Melde unbefugte Nutzung an support@innfeel.app."] },
      { h: "3. Nutzerinhalte", body: ["Du behältst das Eigentum an deinen Auren, Fotos, Videos, Texten, Audiomemos, Tagebucheinträgen und anderen Inhalten. Mit der Übermittlung gewährst du uns eine weltweite, nicht-exklusive, unentgeltliche, unterlizenzierbare Lizenz, sie ausschließlich zum Betrieb, zur Verbesserung und Sicherung des Dienstes zu nutzen. Lizenz endet mit Löschung, außer 30-Tage-Backups, bereits geteilte Inhalte und gesetzliche Pflichten.", "Du bist für deine Inhalte verantwortlich. Verboten sind illegale, verleumderische, belästigende, sexuell explizite Inhalte mit Minderjährigen, verletzende oder hasserfüllte Inhalte."] },
      { h: "4. Zulässige Nutzung", body: ["Verboten: Reverse Engineering, Scraping, Umgehung von Sicherheit/Reziprozität, Identitätsbetrug, Spam/Belästigung, Malware, unbefugter Weiterverkauf, Missbrauch von KI-Funktionen zur Erzeugung schädlicher, illegaler oder irreführender Inhalte."] },
      { h: "5. Pläne, Abonnements, Abrechnung und KEINE Rückerstattung", body: [
        "InnFeel bietet drei Pläne: **Free**, **Pro**-Abonnement und **Zen**-Abonnement. Indikative Preise im Euroraum: **Pro 4,99 €/Monat** und **Zen 12,99 €/Monat**, inkl. Steuern wo anwendbar. Lokale Preise, Währungen und Einführungsangebote werden im App beim Checkout angezeigt und gelten.",
        "Jeder Plan schaltet unterschiedliche Kontingente und Funktionen frei (insbesondere: tägliche KI-Credits — derzeit 5/Tag Pro und 20/Tag Zen, geteilt zwischen KI-Coach und Geleitetem Tagebuch; Geleitete Meditation; Atemrituale; Streak Freeze; HD-Reels; Close Friends; usw.). Tägliche KI-Kontingente werden jeden Kalendertag in deiner Zeitzone zurückgesetzt — **ungenutzte Credits verfallen**. Wir können Kontingente anpassen, um den Dienst stabil zu halten; wesentliche Reduzierungen werden mitgeteilt.",
        "Pro und Zen werden über Apple App Store oder Google Play wiederkehrend abgerechnet. Automatische Verlängerung. Streak-Freeze-Pakete und andere Einmalkäufe sind nicht erstattungsfähige Digitalgüter, die bei Nutzung verbraucht werden.",
        "**Keine Rückerstattungen.** Außer wenn zwingendes Recht dies erfordert, **sind alle Zahlungen endgültig und nicht erstattungsfähig, einschließlich begonnener Abrechnungsperioden, ungenutzter Zeit, versehentlicher Verlängerungen, Downgrades oder ungenutzter KI-Credits**. Testzeiträume werden automatisch in zahlungspflichtige Abos umgewandelt.",
        "**Du bist selbst für die Kündigung verantwortlich** beim jeweiligen Anbieter (Apple/Google). Upgrades sofort, Downgrades zum nächsten Zyklus.",
        "Konto-Löschung **kündigt kein** Abo bei Apple/Google — separat kündigen. Keine Rückerstattungen für bezahlte Perioden.",
        "EU/UK: Mit dem Abschluss verlangst du ausdrücklich die sofortige Ausführung und verzichtest, soweit zulässig, auf dein 14-tägiges Widerrufsrecht.",
      ] },
      { h: "6. KI-Funktionen, Wellness-Tools und DEINE Verantwortung", body: [
        "InnFeel enthält KI-basierte Funktionen (den „KI-Wellness-Coach\" mit Anthropic Claude Sonnet 4.5; KI-Geleitetes Tagebuch; tägliche KI-Insights; Spracherkennung; Aura-, Stimmungs- und Mustererkennung) sowie geleitete Wellness-Rituale (Atemübungen, Geleitete Meditation, Streak Freeze, Gamification, Bestenlisten). Sie sind ausschließlich für **emotionale Selbstreflexion, Journaling und Unterhaltung** bestimmt.",
        "**Du erkennst an und akzeptierst:** (a) KI-Ausgaben werden automatisch von Drittanbieter-Modellen erzeugt und können **falsch, ungenau, voreingenommen, veraltet, halluziniert, unangemessen oder schädlich** sein; (b) **du bist allein verantwortlich**, jede KI-Empfehlung zu lesen, zu bewerten, zu interpretieren und zu überprüfen, bevor du handelst — mit eigenem Urteilsvermögen und, im Zweifel, einem qualifizierten Fachmann; (c) InnFeel **stellt keine bereit und ist nicht haftbar** für Entscheidungen, Handlungen, Unterlassungen, Schäden oder Folgen aus deinem Vertrauen auf KI-Ausgaben oder Wellness-Rituale; (d) KI-Ausgaben sind **kein personalisierter medizinischer, psychologischer, psychiatrischer, rechtlicher, finanzieller oder therapeutischer Rat**, auch wenn sie so formuliert sind.",
        "**InnFeel und seine Werkzeuge (KI-Coach, Atem, Meditation, Geleitetes Tagebuch, Aura-/Stimmungs-Analytics, Mustererkennung usw.) ERSETZEN NICHT** einen approbierten Arzt, Psychiater, Psychologen, Psychotherapeuten, Berater, Ernährungsberater, Sozialarbeiter, eine Krisenhotline oder ein qualifiziertes psychisches/medizinisches Fachpersonal. Sie diagnostizieren, behandeln, heilen oder verhindern keine Krankheit.",
        "**Bei Belastung, Suizidgedanken, Selbstverletzung, schwerer Angst, Panik, Suchtrückfall, Missbrauch oder einem medizinischen oder psychiatrischen Notfall: höre sofort auf, InnFeel zu nutzen, und kontaktiere den Notdienst oder einen qualifizierten Fachmann.** Beispiele: Deutschland 112 / Telefonseelsorge 0800 1110111; EU 112; UK 999 / Samaritans 116 123; USA & Kanada 911 / 988.",
        "KI-Funktionen können **vorübergehend langsam, nicht verfügbar, limitiert, geändert oder ohne Vorwarnung entfernt werden**. Wir können unsichere KI-Anfragen moderieren oder blockieren.",
        "Wir protokollieren KI-Konversationen und Tagebuchinhalte zum Betrieb, zur Sicherheit und Qualitätsverbesserung. Wir verwenden private Inhalte nicht zum Training von Drittanbieter-KI-Basismodellen. Siehe Datenschutzerklärung.",
        "**Mit der Nutzung jeder KI-Funktion oder jedes Wellness-Rituals erteilst du deine informierte Zustimmung zu allem oben Genannten und bestätigst, dass du dich nicht für medizinische, psychiatrische oder Notfallversorgung auf InnFeel verlässt.**",
      ] },
      { h: "7. Änderungen des Dienstes und der Preise", body: ["Wir können Funktionen (inkl. KI-Kontingente) ergänzen, ändern oder entfernen und Preise anpassen. Wesentliche Preisänderungen ab nächstem Verlängerungszyklus."] },
      { h: "8. Beendigung", body: ["Du kannst dein Konto jederzeit löschen. Wir können bei Verstößen, Risiken, KI-Missbrauch oder legitimen Gründen sofort sperren. Abschnitte 3, 5, 6, 9, 10 und 11 überdauern die Beendigung."] },
      { h: "9. Haftungsausschluss", body: ["InnFeel wird „WIE BESEHEN\" und „WIE VERFÜGBAR\" bereitgestellt. Im gesetzlich zulässigen Höchstmaß schließen wir alle Garantien aus. InnFeel ist **kein Medizinprodukt**, gibt keine medizinische/psychologische/psychiatrische Beratung, diagnostiziert/behandelt nichts, und **ersetzt keinen qualifizierten Fachmann** (Abschnitt 6). Wir garantieren nicht, dass KI-Ausgaben korrekt, sicher oder vollständig sind. In Krisen: Notdienst kontaktieren."] },
      { h: "10. Haftungsbeschränkung", body: ["Im gesetzlich zulässigen Höchstmaß haften wir nicht für indirekte, zufällige, besondere, Folge- oder Strafschäden, noch für entgangene Gewinne, Daten, Reputation, Chancen oder Schäden aus deinem Vertrauen auf KI-Ausgaben. Gesamthaftung begrenzt auf den höheren Betrag von (a) der in den letzten 12 Monaten gezahlten Summe oder (b) 50 USD."] },
      { h: "11. Freistellung", body: ["Du verpflichtest dich, uns von Ansprüchen freizustellen, die aus deinen Inhalten, deiner Nutzung, deinem Vertrauen auf KI-Ausgaben oder Verstößen gegen diese Bedingungen entstehen."] },
      { h: "12. Drittdienste", body: ["Der Dienst integriert Dritte (Apple/Google IAP, RevenueCat, Apple Music, Spotify, Cloudflare R2, Expo Push, Resend, Anthropic Claude, OpenAI u.a.). Deren Bedingungen gelten für ihre Teile."] },
      { h: "13. Anwendbares Recht & Streitigkeiten", body: ["Es gilt das Recht des Landes unseres Hauptsitzes, unbeschadet zwingender Verbraucherrechte deines Landes."] },
      { h: "14. Zusätzliche Apple/Google-Bedingungen", body: ["Wenn du die App bei Apple/Google heruntergeladen hast, bestehen diese Bedingungen zwischen dir und uns. Apple und Google sind Drittbegünstigte."] },
      { h: "15. Änderungen der Bedingungen", body: ["Wir können diese Bedingungen aktualisieren. Wesentliche Änderungen werden mind. 14 Tage vorher in der App angekündigt. Fortgesetzte Nutzung gilt als Zustimmung."] },
    ],
    contactIntro: "Fragen? E-Mail",
    contactEmail: "support@innfeel.app",
  },

  pt: {
    title: "InnFeel — Termos de Serviço",
    effective: "Data de vigência: 7 de junho de 2025",
    intro: "Estes Termos regem o teu acesso e uso da aplicação InnFeel e serviços relacionados (o \"Serviço\"), operado pela InnFeel (\"nós\"). Ao criares conta ou usares InnFeel, aceitas estes Termos. Se não concordas, não uses o Serviço.",
    sections: [
      { h: "1. Quem pode usar InnFeel", body: ["Deves ter pelo menos 13 anos (16 no EEE/RU quando exigido) e capacidade para contratar."] },
      { h: "2. A tua conta", body: ["És responsável pela confidencialidade das credenciais e atividade na tua conta. Reporta usos não autorizados a support@innfeel.app."] },
      { h: "3. Conteúdo do utilizador", body: ["Manténs a propriedade das tuas auras, fotos, vídeos, textos, notas de áudio, entradas de diário e demais conteúdo. Ao submeteres, concedes-nos uma licença mundial, não exclusiva, gratuita e sublicenciável apenas para operar, melhorar e proteger o Serviço. Termina ao apagares, salvo backups (≤ 30 dias), conteúdo já partilhado e obrigações legais.", "És o único responsável pelo teu conteúdo. Proibido publicar conteúdo ilegal, difamatório, assediante, sexualmente explícito com menores, infrator ou de ódio."] },
      { h: "4. Uso aceitável", body: ["Proibido: engenharia reversa, scraping, contornar segurança/reciprocidade, personificação, spam/assédio, malware, revenda sem autorização, abuso das funções de IA para gerar conteúdo prejudicial, ilegal ou enganoso."] },
      { h: "5. Planos, subscrições, faturação e política de NÃO reembolso", body: [
        "InnFeel oferece três planos: **Gratuito**, subscrição **Pro** e subscrição **Zen**. Preços indicativos zona euro: **Pro 4,99 €/mês** e **Zen 12,99 €/mês**, impostos incluídos quando aplicáveis. Os preços locais, divisas e ofertas mostrados na app no checkout prevalecem.",
        "Cada plano desbloqueia quotas e funcionalidades distintas (créditos IA diários — atualmente 5/dia Pro e 20/dia Zen, partilhados entre Coach IA e Diário Guiado; Meditação Guiada; Respiração; Streak Freeze; reels HD; Close Friends; etc.). Quotas IA reiniciam todos os dias civis no teu fuso horário — **créditos não usados não transitam**.",
        "Pro e Zen são faturados recorrentemente via Apple/Google. Renovação automática. Pacotes Streak Freeze e outras compras únicas são bens digitais não reembolsáveis.",
        "**Sem reembolsos.** Salvo lei imperativa, **todos os pagamentos são definitivos, incluindo períodos iniciados, tempo não usado, renovações acidentais, downgrades ou créditos IA não usados**. Períodos de teste convertem automaticamente.",
        "**És responsável por cancelar** com o fornecedor (Apple/Google). Upgrades imediatos, downgrades no ciclo seguinte.",
        "Apagar a conta InnFeel **não cancela** subscrições — cancela-as separadamente.",
        "UE/RU: ao subscreveres solicitas execução imediata e renuncias, na medida permitida, ao direito de retratação de 14 dias.",
      ] },
      { h: "6. Funcionalidades de IA, ferramentas de bem-estar e A TUA responsabilidade", body: [
        "InnFeel inclui funcionalidades baseadas em IA (o \"Coach de Bem-estar IA\" com Anthropic Claude Sonnet 4.5; Diário Guiado com IA; insights diários; transcrição de voz; análises de Aura, humor e padrões) e rituais guiados (Respiração, Meditação Guiada, Streak Freeze, gamificação, classificações). Destinam-se **apenas a introspeção emocional, journaling e entretenimento**.",
        "**Reconheces, compreendes e aceitas que:** (a) as saídas de IA são geradas automaticamente por modelos de terceiros e podem ser **incorretas, imprecisas, enviesadas, desatualizadas, alucinadas, inadequadas ou prejudiciais**; (b) **és o único responsável** por ler, avaliar, interpretar e verificar qualquer sugestão antes de agir, usando o teu próprio julgamento e consultando um profissional qualificado em caso de dúvida; (c) InnFeel **não fornece nem é responsável** por qualquer decisão, ação, omissão, dano, perda ou consequência decorrente do teu recurso às saídas de IA ou rituais; (d) as saídas de IA **não são aconselhamento médico, psicológico, psiquiátrico, jurídico, financeiro ou terapêutico personalizado**.",
        "**InnFeel e as suas ferramentas (Coach IA, Respiração, Meditação, Diário Guiado, análises Aura/humor, insights de padrões, etc.) NÃO substituem** um médico, psiquiatra, psicólogo, psicoterapeuta, conselheiro, nutricionista, assistente social, linha de crise ou qualquer profissional qualificado de saúde mental, médica ou de emergência.",
        "**Em caso de mal-estar, pensamentos suicidas, autolesão, ansiedade severa, pânico, recaída adictiva, abuso ou qualquer emergência médica/psiquiátrica, deixa de usar InnFeel imediatamente e contacta serviços de emergência ou um profissional qualificado.** Exemplos: Portugal 112 / SOS Voz Amiga 213 544 545; UE 112; RU 999 / Samaritans 116 123; EUA & Canadá 911 / 988.",
        "As funcionalidades de IA podem ser **temporariamente lentas, indisponíveis, limitadas, modificadas ou removidas sem aviso** por razões de segurança, técnicas ou comerciais.",
        "Registamos conversas de IA e conteúdo do diário para operar o Serviço, garantir segurança, prevenir abusos e melhorar a qualidade. Não usamos os teus conteúdos privados para treinar modelos fundacionais de IA de terceiros.",
        "**Ao usares qualquer funcionalidade de IA ou ritual de bem-estar dás o teu consentimento informado a tudo o que precede e confirmas que não dependes do InnFeel para cuidados médicos, psiquiátricos ou de emergência.**",
      ] },
      { h: "7. Alterações do Serviço e preços", body: ["Podemos acrescentar, modificar ou remover funcionalidades (incluindo quotas IA) e alterar preços. Alterações importantes aplicam-se no próximo ciclo."] },
      { h: "8. Término", body: ["Podes apagar a conta a qualquer momento. Podemos suspender ou terminar imediatamente em caso de violação, risco, abuso de IA ou motivos legítimos. Secções 3, 5, 6, 9, 10 e 11 sobrevivem."] },
      { h: "9. Exclusões", body: ["InnFeel é fornecido \"TAL COMO ESTÁ\" e \"CONFORME DISPONIBILIDADE\". Rejeitamos todas as garantias no máximo permitido. InnFeel **não é dispositivo médico**, não fornece aconselhamento médico/psicológico/psiquiátrico, não diagnostica nem trata, e **não substitui um profissional qualificado** (Secção 6). Não garantimos exatidão/segurança/completude das saídas de IA. Em crise: contacta serviços de emergência."] },
      { h: "10. Limitação de responsabilidade", body: ["No máximo permitido, não seremos responsáveis por danos indiretos, incidentais, especiais, consequentes, exemplares ou punitivos, nem por perda de lucros, dados, reputação, oportunidades ou danos do teu recurso às saídas de IA. Responsabilidade agregada limitada ao maior entre (a) o pago nos últimos 12 meses ou (b) 50 USD."] },
      { h: "11. Indemnização", body: ["Concordas em defender-nos e indemnizar-nos por reclamações decorrentes do teu conteúdo, uso do Serviço, recurso às saídas de IA ou violação destes Termos."] },
      { h: "12. Serviços de terceiros", body: ["Integramos terceiros (IAP Apple/Google, RevenueCat, Apple Music, Spotify, Cloudflare R2, Expo Push, Resend, Anthropic Claude, OpenAI etc.). As suas condições aplicam-se."] },
      { h: "13. Lei aplicável e litígios", body: ["Termos regidos pela lei do país da nossa sede principal, sem prejuízo de leis de consumo imperativas."] },
      { h: "14. Condições Apple / Google", body: ["Se descarregaste a app da Apple/Google, estes Termos são entre ti e nós. Apple e Google são beneficiários terceiros."] },
      { h: "15. Alterações aos Termos", body: ["Podemos atualizá-los. Alterações importantes notificadas com pelo menos 14 dias de antecedência. Uso continuado implica aceitação."] },
    ],
    contactIntro: "Perguntas? Email",
    contactEmail: "support@innfeel.app",
  },

  ar: {
    title: "InnFeel — شروط الخدمة",
    effective: "تاريخ السريان: 7 يونيو 2025",
    intro: "تحكم هذه الشروط وصولك إلى تطبيق InnFeel والخدمات المرتبطة (\"الخدمة\") التي تشغلها InnFeel (\"نحن\"). بإنشاء حساب أو استخدام InnFeel فإنك توافق على هذه الشروط. إذا لم توافق، فلا تستخدم الخدمة.",
    sections: [
      { h: "1. من يمكنه استخدام InnFeel", body: ["يجب أن يكون عمرك 13 عامًا على الأقل (16 في المنطقة الاقتصادية الأوروبية/المملكة المتحدة عند الاقتضاء) وقادرًا على إبرام عقد."] },
      { h: "2. حسابك", body: ["أنت مسؤول عن سرية بيانات الاعتماد وأي نشاط على حسابك. أبلغنا عن أي استخدام غير مصرح به عبر support@innfeel.app."] },
      { h: "3. محتوى المستخدم", body: ["تحتفظ بملكية هالاتك وصورك وفيديوهاتك ونصوصك وملاحظاتك الصوتية وتدويناتك وغيرها. بتقديمها تمنحنا ترخيصًا عالميًا غير حصري ومجانيًا وقابلًا للترخيص من الباطن لتشغيل وتحسين وتأمين الخدمة فقط. ينتهي الترخيص عند الحذف، باستثناء النسخ الاحتياطية (حتى 30 يومًا)، والمحتوى المشارك بالفعل، والالتزامات القانونية.", "أنت وحدك مسؤول عن محتواك. يُحظر نشر أي محتوى غير قانوني أو تشهيري أو تحرشي أو جنسي صريح يتعلق بالقصر أو منتهك للحقوق أو يحض على الكراهية."] },
      { h: "4. الاستخدام المقبول", body: ["يُحظر: الهندسة العكسية، الاستخراج الآلي، تجاوز الأمان أو قاعدة المعاملة بالمثل، انتحال الشخصية، الإزعاج/التحرش، إدخال برامج ضارة، إعادة البيع دون إذن، إساءة استخدام ميزات الذكاء الاصطناعي لإنشاء محتوى ضار أو غير قانوني أو مضلل."] },
      { h: "5. الخطط والاشتراكات والفوترة وسياسة عدم الاسترداد", body: [
        "يقدم InnFeel ثلاث خطط: **مجانية**، اشتراك **Pro**، واشتراك **Zen**. الأسعار الإرشادية في منطقة اليورو: **Pro 4.99 يورو/شهر** و**Zen 12.99 يورو/شهر**، شاملة الضرائب حيثما ينطبق. تسود الأسعار المحلية والعملات والعروض الترويجية المعروضة في التطبيق عند الدفع.",
        "تفتح كل خطة حصصًا وميزات مختلفة (لا سيما: أرصدة الذكاء الاصطناعي اليومية — حاليًا 5/يوم لـ Pro و20/يوم لـ Zen، مشتركة بين Coach AI واليوميات الموجهة؛ موضوعات التأمل الموجه؛ التنفس؛ تجميد السلسلة؛ مقاطع HD؛ الأصدقاء المقربون؛ إلخ). تُعاد ضبط حصص الذكاء الاصطناعي يوميًا — **الأرصدة غير المستخدمة لا تُرحّل**.",
        "يُفوتر Pro وZen بشكل متكرر عبر Apple/Google. تتجدد الاشتراكات تلقائيًا. حزم تجميد السلسلة وغيرها من المشتريات لمرة واحدة هي سلع رقمية غير قابلة للاسترداد.",
        "**لا يوجد استرداد.** باستثناء ما يقتضيه القانون، **جميع المدفوعات نهائية وغير قابلة للاسترداد، بما في ذلك الفترات التي بدأت بالفعل أو الوقت غير المستخدم أو التجديدات غير المقصودة أو خفض الخطة أو أرصدة الذكاء الاصطناعي غير المستخدمة**.",
        "**أنت مسؤول عن إلغاء اشتراكك** مع المزود (Apple/Google). الترقيات فورية والتخفيضات في الدورة التالية.",
        "حذف حساب InnFeel **لا يُلغي** اشتراكات Apple/Google — يجب إلغاؤها بشكل منفصل.",
        "الاتحاد الأوروبي/المملكة المتحدة: بالاشتراك تطلب التنفيذ الفوري وتتنازل، في الحدود المسموح بها، عن حق الانسحاب لمدة 14 يومًا.",
      ] },
      { h: "6. ميزات الذكاء الاصطناعي وأدوات العافية ومسؤوليتك", body: [
        "يتضمن InnFeel ميزات قائمة على الذكاء الاصطناعي (\"مدرب العافية بالذكاء الاصطناعي\" المدعوم بـ Anthropic Claude Sonnet 4.5؛ اليوميات الموجهة بالذكاء الاصطناعي؛ الرؤى اليومية؛ النسخ الصوتي؛ تحليلات الهالة والمزاج والأنماط) وطقوس عافية موجهة (التنفس، التأمل الموجه، تجميد السلسلة، التلعيب، لوحات المتصدرين). هذه الميزات مخصصة **للتأمل العاطفي والتدوين والترفيه فقط**.",
        "**أنت تقر وتفهم وتقبل أن:** (أ) مخرجات الذكاء الاصطناعي يتم إنشاؤها تلقائيًا بواسطة نماذج تابعة لجهات خارجية وقد تكون **خاطئة أو غير دقيقة أو متحيزة أو قديمة أو مهلوسة أو غير ملائمة أو ضارة**؛ (ب) **أنت وحدك المسؤول** عن قراءة وتقييم وتفسير والتحقق من أي اقتراح قبل التصرف بناءً عليه، باستخدام حكمك الخاص واستشارة أخصائي مؤهل عند الشك؛ (ج) InnFeel **لا توفر ولا تتحمل المسؤولية** عن أي قرار أو فعل أو إغفال أو ضرر أو خسارة أو عاقبة ناجمة عن اعتمادك على مخرجات الذكاء الاصطناعي أو طقوس العافية؛ (د) مخرجات الذكاء الاصطناعي **ليست نصيحة طبية أو نفسية أو نفس‑طبية أو قانونية أو مالية أو علاجية مخصصة**، حتى لو صيغت كذلك.",
        "**لا يحل InnFeel وأدواته (مدرب الذكاء الاصطناعي، التنفس، التأمل، اليوميات الموجهة، تحليلات الهالة/المزاج، رؤى الأنماط، إلخ) محل**: طبيب مرخص، طبيب نفسي، أخصائي نفسي، معالج نفسي، مستشار، أخصائي تغذية، أخصائي اجتماعي، خط مساعدة في الأزمات، أو أي محترف صحي/طبي/طوارئ مؤهل. لا تشخّص ولا تعالج ولا تشفي ولا تمنع أي مرض.",
        "**إذا كنت تعاني من ضائقة أو أفكار انتحارية أو رغبات إيذاء النفس أو قلق شديد أو ذعر أو انتكاسة إدمان أو إساءة أو أي طارئ طبي أو نفسي، توقف فورًا عن استخدام InnFeel واتصل بخدمات الطوارئ المحلية أو محترف مؤهل.** أمثلة: الاتحاد الأوروبي 112؛ المملكة المتحدة 999 / Samaritans 116 123؛ الولايات المتحدة وكندا 911 / 988؛ خدمات الطوارئ الوطنية في بلدك.",
        "قد تكون ميزات الذكاء الاصطناعي **بطيئة أو غير متاحة أو محدودة أو معدلة أو مزالة دون إشعار**.",
        "نسجل محادثات الذكاء الاصطناعي ومحتوى اليوميات لتشغيل الخدمة وضمان السلامة ومنع الإساءة وتحسين الجودة. لا نستخدم محتواك الخاص لتدريب نماذج الذكاء الاصطناعي الأساسية لجهات خارجية.",
        "**باستخدام أي ميزة من ميزات الذكاء الاصطناعي أو طقس عافية فإنك تعطي موافقتك المستنيرة على كل ما سبق وتؤكد أنك لا تعتمد على InnFeel للحصول على رعاية طبية أو نفسية أو طارئة.**",
      ] },
      { h: "7. تغييرات في الخدمة والأسعار", body: ["قد نضيف أو نعدل أو نزيل ميزات (بما في ذلك حصص الذكاء الاصطناعي) ونغير الأسعار. تسري التغييرات الجوهرية من الدورة التالية."] },
      { h: "8. الإنهاء", body: ["يمكنك حذف حسابك في أي وقت. يمكننا التعليق أو الإنهاء فورًا عند الانتهاك أو المخاطر أو إساءة استخدام الذكاء الاصطناعي. تظل الأقسام 3 و5 و6 و9 و10 و11 سارية."] },
      { h: "9. إخلاء المسؤولية", body: ["يُقدم InnFeel \"كما هو\" و\"حسب التوفر\". إلى أقصى حد يسمح به القانون، نُخلي مسؤوليتنا عن جميع الضمانات. InnFeel **ليس جهازًا طبيًا**، ولا يقدم نصيحة طبية/نفسية/نفس‑طبية، ولا يشخص ولا يعالج، **ولا يحل محل محترف مؤهل** (القسم 6). لا نضمن دقة/سلامة/اكتمال مخرجات الذكاء الاصطناعي. في الأزمات: اتصل بخدمات الطوارئ."] },
      { h: "10. حد المسؤولية", body: ["إلى أقصى حد يسمح به القانون، لن نكون مسؤولين عن أي أضرار غير مباشرة أو عرضية أو خاصة أو تبعية أو مثالية أو عقابية، ولا عن خسارة الأرباح أو البيانات أو السمعة أو أي ضرر ناجم عن اعتمادك على مخرجات الذكاء الاصطناعي. تقتصر مسؤوليتنا الإجمالية على الأكبر من (أ) المبلغ المدفوع خلال 12 شهرًا أو (ب) 50 دولارًا أمريكيًا."] },
      { h: "11. التعويض", body: ["توافق على الدفاع عنا وتعويضنا عن أي مطالبات ناشئة عن محتواك أو استخدامك للخدمة أو اعتمادك على مخرجات الذكاء الاصطناعي أو انتهاكك لهذه الشروط."] },
      { h: "12. خدمات الطرف الثالث", body: ["نحن ندمج أطرافًا ثالثة (IAP من Apple/Google، RevenueCat، Apple Music، Spotify، Cloudflare R2، Expo Push، Resend، Anthropic Claude، OpenAI، إلخ). تنطبق شروطهم على أجزائهم."] },
      { h: "13. القانون المطبق والنزاعات", body: ["تخضع هذه الشروط لقوانين بلد مقرنا الرئيسي، دون المساس بالقوانين الاستهلاكية الإلزامية في اختصاصك."] },
      { h: "14. شروط Apple / Google الإضافية", body: ["إذا حملت التطبيق من Apple أو Google، فإن هذه الشروط بينك وبيننا. Apple وGoogle مستفيدان ثانويان."] },
      { h: "15. تغييرات الشروط", body: ["قد نحدّثها. يتم الإخطار بالتغييرات الجوهرية في التطبيق قبل 14 يومًا على الأقل. الاستخدام المستمر يعني القبول."] },
    ],
    contactIntro: "أسئلة؟ البريد الإلكتروني",
    contactEmail: "support@innfeel.app",
  },
};

// --------------------- PRIVACY POLICY ---------------------
const PRIVACY: Record<LocaleCode, LegalDoc> = {
  en: {
    title: "InnFeel — Privacy Policy",
    effective: "Effective date: " + EFFECTIVE_DATE,
    intro: "This Privacy Policy explains what personal data InnFeel (\"we\") collects, why, how we use and share it, and the rights you have. It applies to everyone using the InnFeel app worldwide and complies with GDPR, UK GDPR, CCPA/CPRA, LGPD, PIPEDA, and equivalent laws.",
    sections: [
      { h: "1. Data controller", body: ["InnFeel is the controller. Contact: support@innfeel.app."] },
      { h: "2. What we collect", body: ["• **Account data**: name, email, hashed password, avatar, creation date.", "• **Auras & interactions**: emotion, word, intensity, optional photo/video/audio, text, music reference, privacy setting, reactions, comments, friendships, messages.", "• **AI Coach & journal content**: your prompts, voice transcriptions and replies for AI Coach and Guided Journaling — used to operate, secure and improve the Service. Not used to train third-party foundational AI models.", "• **Device & technical data**: push token, platform, language, app version, crash diagnostics.", "• **Subscription data**: plan (Free/Pro/Zen), status and expiry from Apple/Google/RevenueCat. We do not store your full card number.", "• **Minimal usage analytics**: streaks, AI quota usage, aggregated feature usage. No cross-app tracking."] },
      { h: "3. Why we use it (GDPR legal bases)", body: ["• **To provide the Service** (contract): authenticate, store auras, deliver messages, generate stats, run AI Coach and Guided Journaling.", "• **To personalise wellness insights** (contract): a short daily sentence and AI replies via an AI provider based on your input (no name/email/identifier sent to the AI).", "• **To send notifications** (legitimate interest/consent): reminders, reactions, comments, messages, friend activity. Any category can be disabled in Settings.", "• **To process payments** (contract): via Apple IAP, Google Play Billing, RevenueCat.", "• **To secure and improve the Service** (legitimate interest / legal obligation): abuse prevention, fraud detection, AI safety moderation."] },
      { h: "4. Who we share data with", body: ["• Your friends — only data you choose to share.", "• Processors: MongoDB Atlas, cloud provider, Cloudflare R2, Expo (push), Apple/Google/RevenueCat, AI providers (Anthropic, OpenAI), iTunes & Spotify search, email sender (Resend/SendGrid).", "• Authorities: only on valid legal process.", "**We do NOT sell your personal data.**"] },
      { h: "5. International transfers", body: ["If data leaves your country we rely on Standard Contractual Clauses or equivalent safeguards."] },
      { h: "6. Retention", body: ["• Account: while active.", "• Auras/messages: until you delete them or your account.", "• AI Coach & journal entries: kept while account active; deletion within 30 days of account deletion (subject to backups and legal obligations).", "• After deletion: erased, except 30-day backups and records we must keep by law."] },
      { h: "7. Your rights", body: ["Depending on your country: access, rectify, erase, restrict, object, port, withdraw consent, lodge a complaint. California: right to know, delete, correct, opt-out of sale/sharing (we don't sell), non-discrimination. Use Settings → Account or email support@innfeel.app. Response within 30 days."] },
      { h: "8. Security", body: ["TLS in transit, bcrypt for passwords, limited access, regular updates. No system is 100% secure; use a strong unique password."] },
      { h: "9. Children", body: ["Not directed to children under 13 (or 16 in EEA/UK). We do not knowingly collect their data. Contact support@innfeel.app to report."] },
      { h: "10. Cookies & similar tech", body: ["Essential device storage for tokens and preferences. No ad cookies, no cross-site trackers."] },
      { h: "11. Changes", body: ["Material changes are notified in-app. The effective date reflects the last update."] },
      { h: "12. Contact & complaints", body: ["support@innfeel.app. EEA users may also contact their local Data Protection Authority."] },
    ],
    contactIntro: "Questions or complaints?",
    contactEmail: "support@innfeel.app",
  },
  fr: {
    title: "InnFeel — Politique de Confidentialité",
    effective: "Date d'effet : 7 juin 2025",
    intro: "Cette Politique explique quelles données personnelles InnFeel (« nous ») collecte, pourquoi, comment nous les utilisons et partageons, et vos droits. Elle s'applique mondialement et respecte le RGPD, le RGPD UK, le CCPA/CPRA, la LGPD, la PIPEDA et lois équivalentes.",
    sections: [
      { h: "1. Responsable de traitement", body: ["InnFeel est le responsable. Contact : support@innfeel.app."] },
      { h: "2. Ce que nous collectons", body: ["• **Données de compte** : nom, email, mot de passe haché, avatar, date de création.", "• **Auras et interactions** : émotion, mot, intensité, photo/vidéo/audio optionnels, texte, référence musique, confidentialité, réactions, commentaires, amitiés, messages.", "• **Contenus Coach IA et journal** : vos messages, transcriptions vocales et réponses pour le Coach IA et le Journal Guidé — utilisés pour opérer, sécuriser et améliorer le Service. Non utilisés pour entraîner les modèles d'IA fondamentaux tiers.", "• **Données techniques** : token push, plateforme, langue, version de l'app, diagnostics de crash.", "• **Données d'abonnement** : plan (Free/Pro/Zen), statut et expiration depuis Apple/Google/RevenueCat. Nous ne stockons pas votre numéro de carte complet.", "• **Analytique minimale** : streaks, usage des quotas IA, usage agrégé. Pas de tracking inter-apps."] },
      { h: "3. Pourquoi (bases légales RGPD)", body: ["• **Fournir le Service** (contrat) : authentification, stockage des auras, messages, stats, Coach IA, Journal Guidé.", "• **Personnaliser les insights bien-être** (contrat) : phrase quotidienne et réponses IA basées sur votre saisie (aucun nom/email/identifiant envoyé à l'IA).", "• **Envoyer des notifications** (intérêt légitime/consentement) : rappels, réactions, commentaires, messages, activité amis. Désactivable.", "• **Traiter les paiements** (contrat) : via IAP Apple, Google Play, RevenueCat.", "• **Sécuriser et améliorer le Service** (intérêt légitime/obligation légale) : prévention abus, fraude, modération de sécurité IA."] },
      { h: "4. Avec qui nous partageons", body: ["• Vos amis — uniquement les données que vous partagez.", "• Sous-traitants : MongoDB Atlas, hébergeur cloud, Cloudflare R2, Expo (push), Apple/Google/RevenueCat, fournisseurs IA (Anthropic, OpenAI), iTunes & Spotify Search, émetteur email (Resend/SendGrid).", "• Autorités : uniquement sur demande légale valide.", "**Nous NE vendons PAS vos données personnelles.**"] },
      { h: "5. Transferts internationaux", body: ["Si des données quittent votre pays, nous utilisons les Clauses Contractuelles Types ou garanties équivalentes."] },
      { h: "6. Durée de conservation", body: ["• Compte : tant qu'il est actif.", "• Auras/messages : jusqu'à suppression par vous.", "• Coach IA & entrées de journal : conservés tant que le compte est actif ; supprimés dans les 30 jours après suppression du compte (sauf sauvegardes et obligations légales).", "• Après suppression : effacement, sauf sauvegardes 30 jours et registres légaux obligatoires."] },
      { h: "7. Vos droits", body: ["Selon votre pays : accès, rectification, effacement, limitation, opposition, portabilité, retrait du consentement, réclamation. Californie : droits de savoir, supprimer, corriger, opt-out vente/partage (nous ne vendons pas), non-discrimination. Utilisez Paramètres → Compte ou email support@innfeel.app. Réponse sous 30 jours."] },
      { h: "8. Sécurité", body: ["TLS en transit, bcrypt pour les mots de passe, accès restreint, mises à jour régulières. Aucun système n'est 100% sûr ; utilisez un mot de passe fort et unique."] },
      { h: "9. Enfants", body: ["InnFeel n'est pas destiné aux moins de 13 ans (16 dans l'EEE/RU). Nous ne collectons pas sciemment leurs données. Contactez support@innfeel.app pour signaler."] },
      { h: "10. Cookies et technologies similaires", body: ["Stockage essentiel pour tokens et préférences. Pas de cookies publicitaires ni de traceurs inter-sites."] },
      { h: "11. Modifications", body: ["Les modifications importantes sont notifiées dans l'app. La date d'effet reflète la dernière mise à jour."] },
      { h: "12. Contact et plaintes", body: ["support@innfeel.app. Les utilisateurs UE peuvent aussi contacter leur autorité de protection des données (en France, la CNIL)."] },
    ],
    contactIntro: "Questions ou plaintes ?",
    contactEmail: "support@innfeel.app",
  },
  es: {
    title: "InnFeel — Política de Privacidad",
    effective: "Fecha de vigencia: 7 de junio de 2025",
    intro: "Esta Política explica qué datos personales recopila InnFeel (\"nosotros\"), por qué, cómo los usamos y compartimos, y tus derechos. Aplica mundialmente y cumple con RGPD, UK GDPR, CCPA/CPRA, LGPD, PIPEDA y leyes equivalentes.",
    sections: [
      { h: "1. Responsable del tratamiento", body: ["InnFeel es el responsable. Contacto: support@innfeel.app."] },
      { h: "2. Qué recopilamos", body: ["• **Datos de cuenta**: nombre, email, contraseña hasheada, avatar, fecha de creación.", "• **Auras e interacciones**: emoción, palabra, intensidad, foto/vídeo/audio opcional, texto, música, privacidad, reacciones, comentarios, amistades, mensajes.", "• **Contenido Coach IA y diario**: tus mensajes, transcripciones de voz y respuestas usados para operar, asegurar y mejorar el Servicio. No usados para entrenar modelos fundacionales de IA de terceros.", "• **Datos técnicos**: token push, plataforma, idioma, versión, diagnósticos.", "• **Datos de suscripción**: plan (Free/Pro/Zen), estado y caducidad desde Apple/Google/RevenueCat. No guardamos tu número de tarjeta completo.", "• **Analítica mínima**: rachas, uso de cuotas IA, uso agregado. Sin tracking entre apps."] },
      { h: "3. Por qué (bases legales RGPD)", body: ["• **Prestar el Servicio** (contrato): incluido Coach IA y Diario Guiado.", "• **Personalizar insights de bienestar** (contrato): frase diaria y respuestas IA (sin nombre/email enviados).", "• **Notificaciones** (interés legítimo/consentimiento).", "• **Procesar pagos** (contrato).", "• **Seguridad y mejora** (interés legítimo/obligación legal): incluida moderación de seguridad de IA."] },
      { h: "4. Con quién compartimos", body: ["• Tus amigos — solo lo que eliges compartir.", "• Encargados: MongoDB Atlas, cloud, Cloudflare R2, Expo, Apple/Google/RevenueCat, proveedores IA (Anthropic, OpenAI), iTunes & Spotify Search, email (Resend).", "• Autoridades: solo proceso legal válido.", "**NO vendemos tus datos.**"] },
      { h: "5. Transferencias internacionales", body: ["Cláusulas Contractuales Tipo o equivalentes."] },
      { h: "6. Conservación", body: ["• Cuenta: mientras esté activa.", "• Auras/mensajes: hasta que los borres.", "• Coach IA y entradas de diario: mientras cuenta activa; eliminados a los 30 días tras eliminación de cuenta.", "• Tras eliminación: borrado, salvo backups 30 días y obligaciones legales."] },
      { h: "7. Tus derechos", body: ["Acceso, rectificación, supresión, limitación, oposición, portabilidad, retirada de consentimiento, reclamación. Usa Ajustes → Cuenta o support@innfeel.app. Respuesta en 30 días."] },
      { h: "8. Seguridad", body: ["TLS, bcrypt, acceso restringido, actualizaciones."] },
      { h: "9. Menores", body: ["No dirigido a menores de 13 (16 EEE/RU)."] },
      { h: "10. Cookies y similares", body: ["Almacenamiento esencial. Sin cookies publicitarias."] },
      { h: "11. Cambios", body: ["Cambios importantes notificados en la app."] },
      { h: "12. Contacto", body: ["support@innfeel.app. Usuarios UE pueden contactar a su autoridad de protección de datos (AEPD en España)."] },
    ],
    contactIntro: "¿Preguntas o reclamaciones?",
    contactEmail: "support@innfeel.app",
  },
  it: {
    title: "InnFeel — Informativa sulla Privacy",
    effective: "Data di efficacia: 7 giugno 2025",
    intro: "Questa Informativa spiega quali dati personali raccoglie InnFeel (\"noi\"), perché, come li usiamo e condividiamo, e i tuoi diritti. Si applica in tutto il mondo e rispetta GDPR, UK GDPR, CCPA/CPRA, LGPD, PIPEDA e leggi equivalenti.",
    sections: [
      { h: "1. Titolare del trattamento", body: ["InnFeel è il titolare. Contatto: support@innfeel.app."] },
      { h: "2. Cosa raccogliamo", body: ["• **Dati account**: nome, email, password hashed, avatar, data di creazione.", "• **Auras e interazioni**: emozione, parola, intensità, foto/video/audio opzionali, testo, musica, privacy, reazioni, commenti, amicizie, messaggi.", "• **Contenuti Coach IA e diario**: i tuoi messaggi, trascrizioni vocali e risposte per Coach IA e Diario Guidato. Non usati per addestrare modelli IA di terzi.", "• **Dati tecnici**: push token, piattaforma, lingua, versione, diagnostica.", "• **Dati di abbonamento**: piano (Free/Pro/Zen), stato e scadenza da Apple/Google/RevenueCat. Non conserviamo il numero di carta completo.", "• **Analitica minima**: streak, uso quote IA, uso aggregato."] },
      { h: "3. Perché (basi giuridiche GDPR)", body: ["• **Fornire il Servizio** (contratto): incluso Coach IA e Diario Guidato.", "• **Personalizzare insights** (contratto).", "• **Notifiche** (legittimo interesse/consenso).", "• **Pagamenti** (contratto).", "• **Sicurezza e miglioramento** (legittimo interesse/obbligo legale): inclusa moderazione di sicurezza IA."] },
      { h: "4. Con chi condividiamo", body: ["• I tuoi amici.", "• Responsabili: MongoDB Atlas, cloud, Cloudflare R2, Expo, Apple/Google/RevenueCat, fornitori IA (Anthropic, OpenAI), iTunes & Spotify Search, email (Resend).", "• Autorità: solo con processo legale valido.", "**NON vendiamo i tuoi dati.**"] },
      { h: "5. Trasferimenti internazionali", body: ["Clausole Contrattuali Standard o equivalenti."] },
      { h: "6. Conservazione", body: ["• Account: mentre attivo.", "• Auras/messaggi: fino a cancellazione.", "• Coach IA e voci di diario: mentre account attivo; cancellati entro 30 giorni dalla cancellazione account.", "• Dopo cancellazione: eliminato, salvo backup 30 giorni e obblighi legali."] },
      { h: "7. I tuoi diritti", body: ["Accesso, rettifica, cancellazione, limitazione, opposizione, portabilità, revoca consenso, reclamo. Risposta entro 30 giorni."] },
      { h: "8. Sicurezza", body: ["TLS, bcrypt, accesso limitato, aggiornamenti."] },
      { h: "9. Minori", body: ["Non rivolto ai minori di 13 anni (16 in SEE/UK)."] },
      { h: "10. Cookie e simili", body: ["Archiviazione essenziale. Nessun cookie pubblicitario."] },
      { h: "11. Modifiche", body: ["Modifiche importanti notificate nell'app."] },
      { h: "12. Contatto", body: ["support@innfeel.app. Utenti UE: Garante in Italia."] },
    ],
    contactIntro: "Domande o reclami?",
    contactEmail: "support@innfeel.app",
  },
  de: {
    title: "InnFeel — Datenschutzerklärung",
    effective: "Gültigkeitsdatum: 7. Juni 2025",
    intro: "Diese Datenschutzerklärung erklärt, welche personenbezogenen Daten InnFeel („wir\") erhebt, warum, wie wir sie verwenden und weitergeben, und welche Rechte du hast.",
    sections: [
      { h: "1. Verantwortlicher", body: ["InnFeel. Kontakt: support@innfeel.app."] },
      { h: "2. Was wir erheben", body: ["• **Kontodaten**: Name, E-Mail, gehashtes Passwort, Avatar.", "• **Auren & Interaktionen**: Emotion, Foto/Video/Audio, Reaktionen, Nachrichten.", "• **KI-Coach & Tagebuch-Inhalte**: Eingaben, Sprachtranskriptionen und Antworten für KI-Coach und Geleitetes Tagebuch. Nicht zum Training von Drittanbieter-Basismodellen verwendet.", "• **Technische Daten**: Push-Token, Plattform, Sprache, App-Version.", "• **Abodaten**: Plan (Free/Pro/Zen), Status und Ablauf von Apple/Google/RevenueCat.", "• **Minimale Nutzungsanalyse**: Streaks, KI-Kontingente."] },
      { h: "3. Warum (DSGVO-Rechtsgrundlagen)", body: ["• **Dienst bereitstellen** (Vertrag): inkl. KI-Coach und Geleitetes Tagebuch.", "• **Personalisierung** (Vertrag).", "• **Benachrichtigungen** (berechtigtes Interesse/Einwilligung).", "• **Zahlungen** (Vertrag).", "• **Sicherheit und Verbesserung** (berechtigtes Interesse/Rechtspflicht): inkl. KI-Sicherheitsmoderation."] },
      { h: "4. An wen wir weitergeben", body: ["• Deine Freunde.", "• Auftragsverarbeiter: MongoDB Atlas, Cloud, Cloudflare R2, Expo, Apple/Google/RevenueCat, KI-Anbieter (Anthropic, OpenAI), iTunes & Spotify Search, E-Mail (Resend).", "• Behörden: nur bei gültigem Rechtsverfahren.", "**Wir verkaufen deine Daten NICHT.**"] },
      { h: "5. Internationale Übermittlungen", body: ["Standardvertragsklauseln oder gleichwertige Garantien."] },
      { h: "6. Aufbewahrung", body: ["• Konto: solange aktiv.", "• KI-Coach & Tagebuch-Einträge: aktiv solange Konto besteht; gelöscht binnen 30 Tagen nach Konto-Löschung.", "• Nach Löschung: gelöscht, außer 30-Tage-Backups und gesetzlicher Pflichten."] },
      { h: "7. Deine Rechte", body: ["Auskunft, Berichtigung, Löschung, Einschränkung, Widerspruch, Datenübertragbarkeit, Widerruf, Beschwerde."] },
      { h: "8. Sicherheit", body: ["TLS, bcrypt, eingeschränkter Zugriff, regelmäßige Updates."] },
      { h: "9. Kinder", body: ["Nicht an Kinder unter 13 (16 EWR/UK) gerichtet."] },
      { h: "10. Cookies", body: ["Essenzieller Gerätespeicher. Keine Werbecookies."] },
      { h: "11. Änderungen", body: ["Wesentliche Änderungen werden in der App angekündigt."] },
      { h: "12. Kontakt", body: ["support@innfeel.app. EU-Nutzer können auch ihre Datenschutzbehörde kontaktieren."] },
    ],
    contactIntro: "Fragen oder Beschwerden?",
    contactEmail: "support@innfeel.app",
  },
  pt: {
    title: "InnFeel — Política de Privacidade",
    effective: "Data de vigência: 7 de junho de 2025",
    intro: "Esta Política explica que dados pessoais a InnFeel (\"nós\") recolhe, porquê, como os usamos e partilhamos, e os teus direitos.",
    sections: [
      { h: "1. Responsável pelo tratamento", body: ["InnFeel. Contacto: support@innfeel.app."] },
      { h: "2. O que recolhemos", body: ["• **Dados de conta**: nome, email, palavra-passe hashed, avatar.", "• **Auras e interações**: emoção, palavra, intensidade, foto/vídeo/áudio opcional, texto, música, privacidade, reações, comentários, amizades, mensagens.", "• **Conteúdo Coach IA e diário**: mensagens, transcrições de voz e respostas. Não usados para treinar modelos fundacionais de IA de terceiros.", "• **Dados técnicos**: token push, plataforma, idioma, versão.", "• **Dados de subscrição**: plano (Gratuito/Pro/Zen), estado e expiração via Apple/Google/RevenueCat.", "• **Analítica mínima**: sequências, uso de quotas IA, uso agregado."] },
      { h: "3. Porquê (bases legais RGPD)", body: ["• **Prestar o Serviço** (contrato): incluindo Coach IA e Diário Guiado.", "• **Personalização** (contrato).", "• **Notificações** (interesse legítimo/consentimento).", "• **Pagamentos** (contrato).", "• **Segurança e melhoria** (interesse legítimo/obrigação legal): inclui moderação de segurança IA."] },
      { h: "4. Com quem partilhamos", body: ["• Teus amigos.", "• Subcontratantes: MongoDB Atlas, cloud, Cloudflare R2, Expo, Apple/Google/RevenueCat, fornecedores IA (Anthropic, OpenAI), iTunes & Spotify Search, email (Resend).", "• Autoridades: apenas processo legal válido.", "**NÃO vendemos os teus dados.**"] },
      { h: "5. Transferências internacionais", body: ["Cláusulas Contratuais-Tipo ou equivalentes."] },
      { h: "6. Conservação", body: ["• Conta: enquanto ativa.", "• Coach IA e entradas de diário: enquanto conta ativa; eliminados em 30 dias após eliminação da conta.", "• Após eliminação: apagado, exceto backups 30 dias e obrigações legais."] },
      { h: "7. Os teus direitos", body: ["Acesso, retificação, apagamento, limitação, oposição, portabilidade, retirada de consentimento, reclamação."] },
      { h: "8. Segurança", body: ["TLS, bcrypt, acesso restrito, atualizações."] },
      { h: "9. Crianças", body: ["Não dirigido a menores de 13 (16 EEE/RU)."] },
      { h: "10. Cookies", body: ["Armazenamento essencial. Sem cookies publicitários."] },
      { h: "11. Alterações", body: ["Alterações importantes notificadas na app."] },
      { h: "12. Contacto", body: ["support@innfeel.app. Utilizadores UE: CNPD em Portugal."] },
    ],
    contactIntro: "Perguntas ou reclamações?",
    contactEmail: "support@innfeel.app",
  },
  ar: {
    title: "InnFeel — سياسة الخصوصية",
    effective: "تاريخ السريان: 7 يونيو 2025",
    intro: "تشرح هذه السياسة البيانات الشخصية التي تجمعها InnFeel (\"نحن\")، ولماذا، وكيف نستخدمها ونشاركها، وحقوقك.",
    sections: [
      { h: "1. المسؤول عن البيانات", body: ["InnFeel. الاتصال: support@innfeel.app."] },
      { h: "2. ما نجمعه", body: ["• **بيانات الحساب**: الاسم، البريد، كلمة مرور مجزأة، الصورة الرمزية.", "• **الهالات والتفاعلات**: المشاعر، الكلمة، الشدة، صور/فيديو/صوت اختياري، نص، مرجع موسيقى، الخصوصية، التفاعلات، التعليقات، الصداقات، الرسائل.", "• **محتوى Coach AI واليوميات**: رسائلك ونسخ الصوت والإجابات. لا تُستخدم لتدريب نماذج الذكاء الاصطناعي الأساسية لجهات خارجية.", "• **البيانات التقنية**: رمز الدفع، النظام، اللغة، الإصدار.", "• **بيانات الاشتراك**: الخطة (مجانية/Pro/Zen)، الحالة والانتهاء من Apple/Google/RevenueCat.", "• **تحليلات محدودة**: السلاسل، استخدام حصص الذكاء الاصطناعي، الاستخدام المجمع."] },
      { h: "3. لماذا (الأسس القانونية لـ GDPR)", body: ["• **تقديم الخدمة** (عقد): بما في ذلك Coach AI واليوميات الموجهة.", "• **التخصيص** (عقد).", "• **الإشعارات** (مصلحة مشروعة/موافقة).", "• **المدفوعات** (عقد).", "• **التأمين والتحسين** (مصلحة مشروعة/التزام قانوني): بما في ذلك إشراف سلامة الذكاء الاصطناعي."] },
      { h: "4. مع من نشارك", body: ["• أصدقاؤك.", "• معالجو البيانات: MongoDB Atlas، السحابة، Cloudflare R2، Expo، Apple/Google/RevenueCat، مزودو الذكاء الاصطناعي (Anthropic، OpenAI)، iTunes وSpotify Search، البريد (Resend).", "• السلطات: فقط بموجب إجراء قانوني صحيح.", "**نحن لا نبيع بياناتك الشخصية.**"] },
      { h: "5. النقل الدولي", body: ["البنود التعاقدية القياسية أو ما يعادلها."] },
      { h: "6. مدة الاحتفاظ", body: ["• الحساب: ما دام نشطًا.", "• محتوى Coach AI واليوميات: أثناء نشاط الحساب؛ يُحذف خلال 30 يومًا من حذف الحساب.", "• بعد الحذف: محذوف، باستثناء النسخ الاحتياطية (30 يومًا) والالتزامات القانونية."] },
      { h: "7. حقوقك", body: ["الوصول، التصحيح، المحو، التقييد، الاعتراض، النقل، سحب الموافقة، الشكوى."] },
      { h: "8. الأمان", body: ["TLS، bcrypt، وصول محدود، تحديثات منتظمة."] },
      { h: "9. الأطفال", body: ["غير موجه للأطفال دون 13 عامًا (16 في المنطقة الاقتصادية الأوروبية/المملكة المتحدة)."] },
      { h: "10. ملفات تعريف الارتباط", body: ["تخزين جهاز أساسي. لا توجد ملفات تعريف ارتباط إعلانية."] },
      { h: "11. التغييرات", body: ["يتم إعلام المستخدمين بالتغييرات الجوهرية داخل التطبيق."] },
      { h: "12. الاتصال", body: ["support@innfeel.app."] },
    ],
    contactIntro: "أسئلة أو شكاوى؟",
    contactEmail: "support@innfeel.app",
  },
};

export function getTerms(locale: LocaleCode): LegalDoc { return TERMS[locale] || TERMS.en; }
export function getPrivacy(locale: LocaleCode): LegalDoc { return PRIVACY[locale] || PRIVACY.en; }
