/**
 * Natural-voice narrator powered by the backend's edge-tts endpoint.
 *
 * What this replaces
 *  Before: every breath cue and meditation line went through expo-speech,
 *  which uses the OS-level TTS engine. Quality is highly variable and
 *  often robotic, choppy, with poor rhythm — exactly the user complaint.
 *
 *  Now: we ask `/api/tts/synthesize` for an MP3 generated by Microsoft's
 *  Edge Neural voices (free, no key, neural quality). The backend caches
 *  each (voice, rate, pitch, text) tuple in R2, so the SECOND time the
 *  user hears a given cue it loads instantly.
 *
 * What this exports
 *  • narrate(text, opts) — fire-and-forget speak.
 *  • prefetch(text, opts) — warm the cache before the user reaches a cue.
 *  • stopAll() — cancel any in-flight playback. Always call this when
 *    switching screens or stopping a session.
 *
 * Resilience
 *  We keep expo-speech as a silent fallback. If the backend errors,
 *  the network is down, or the device cannot play the MP3, we degrade
 *  gracefully to the OS voice instead of failing silently — so the
 *  ritual never breaks just because of a flaky network.
 */

import { Audio } from "expo-av";
import * as Speech from "expo-speech";
import { Platform } from "react-native";
import { api } from "./api";
import { currentLocale as getLocale } from "./i18n";

type NarrateOpts = {
  /** ISO-2 locale override. Defaults to current app locale. */
  lang?: string;
  /** Speak rate hint for edge-tts (e.g. "-12%" for slower). */
  rate?: string;
  /** Pitch hint (e.g. "-2Hz"). */
  pitch?: string;
  /** Called after the audio finishes (or fails). */
  onFinish?: () => void;
  /** Volume 0..1 — we lean a bit lower to feel intimate, not loud. */
  volume?: number;
};

// We hold the currently-playing Sound so stopAll() can unload it cleanly.
// Only one narration plays at a time — speech is sequential by design.
let currentSound: Audio.Sound | null = null;
let currentToken: number = 0; // increments on every narrate call to invalidate stale callbacks

/** Best-effort initialiser. iOS needs us to allow audio in silent mode
 *  so the meditation voice plays even when the user has the ringer off
 *  (which is the most common setting at bedtime). */
let audioModeReady = false;
async function ensureAudioMode() {
  if (audioModeReady) return;
  try {
    await Audio.setAudioModeAsync({
      allowsRecordingIOS: false,
      playsInSilentModeIOS: true,
      staysActiveInBackground: false,
      shouldDuckAndroid: true,
      playThroughEarpieceAndroid: false,
    });
    audioModeReady = true;
  } catch {
    // Non-fatal — playback still works in normal mode.
  }
}

async function speakWithExpoSpeech(text: string, opts: NarrateOpts) {
  // OS-level fallback. We tweak rate/pitch to feel less robotic. iOS
  // honours these well; Android quality varies by ROM.
  try {
    Speech.stop();
    Speech.speak(text, {
      language: (opts.lang || getLocale() || "en") as any,
      pitch: 0.96,
      rate: Platform.OS === "ios" ? 0.46 : 0.92,
      volume: opts.volume ?? 0.95,
      onDone: () => opts.onFinish?.(),
      onStopped: () => opts.onFinish?.(),
      onError: () => opts.onFinish?.(),
    });
  } catch {
    opts.onFinish?.();
  }
}

/** Cancel anything currently playing. Idempotent. */
export async function stopAll() {
  currentToken += 1;
  try { Speech.stop(); } catch {}
  if (currentSound) {
    const s = currentSound;
    currentSound = null;
    try { await s.stopAsync(); } catch {}
    try { await s.unloadAsync(); } catch {}
  }
}

/** Speak `text`. Returns when the audio finishes (or fails-fast).
 *  Cheap to call repeatedly — the previous narration is auto-cancelled.
 *  The promise resolves on completion so callers can `await narrate(...)`
 *  if they want to chain cues. */
export async function narrate(text: string, opts: NarrateOpts = {}): Promise<void> {
  if (!text || !text.trim()) return;
  await ensureAudioMode();
  await stopAll();

  const myToken = ++currentToken;
  let resolveDone: () => void = () => {};
  const done = new Promise<void>((res) => { resolveDone = res; });
  const finishOnce = () => {
    if (myToken !== currentToken) return;
    opts.onFinish?.();
    resolveDone();
  };

  try {
    const res = await api<{ url: string; cached: boolean; voice: string }>(
      "/tts/synthesize",
      {
        method: "POST",
        body: {
          text: text.trim(),
          lang: opts.lang || getLocale() || "en",
          rate: opts.rate ?? "-10%",   // slightly slower for breathwork
          pitch: opts.pitch ?? "-2Hz", // a touch warmer
        },
      }
    );
    // If the user navigated away while we were waiting on the network,
    // bail out — playing now would interrupt the next screen's audio.
    if (myToken !== currentToken) return done;

    const { sound } = await Audio.Sound.createAsync(
      { uri: res.url },
      { shouldPlay: true, volume: opts.volume ?? 0.95, isLooping: false },
      (status) => {
        if ("didJustFinish" in (status as any) && (status as any).didJustFinish) {
          finishOnce();
          // Defer unload to a microtask so the status callback can settle.
          setTimeout(() => {
            sound.unloadAsync().catch(() => {});
            if (currentSound === sound) currentSound = null;
          }, 0);
        }
      }
    );
    if (myToken !== currentToken) {
      // Race: stop was called while we were loading. Drop the sound.
      sound.unloadAsync().catch(() => {});
      return done;
    }
    currentSound = sound;
  } catch (err) {
    // Backend or network failure: degrade to expo-speech so the ritual
    // never silently breaks. We log to console for diagnostics only.
    if (__DEV__) console.warn("[narrate] falling back to expo-speech:", err);
    await speakWithExpoSpeech(text, { ...opts, onFinish: finishOnce });
  }
  return done;
}

/** Warm the R2 cache for an upcoming cue. The promise resolves as soon
 *  as the audio is reachable so the next narrate() of this exact text
 *  starts within ~150 ms instead of ~1.5 s. */
export async function prefetch(text: string, opts: NarrateOpts = {}) {
  if (!text || !text.trim()) return;
  try {
    await api("/tts/synthesize", {
      method: "POST",
      body: {
        text: text.trim(),
        lang: opts.lang || getLocale() || "en",
        rate: opts.rate ?? "-10%",
        pitch: opts.pitch ?? "-2Hz",
      },
    });
  } catch {
    // ignore — prefetch is opportunistic.
  }
}
